
= Volet architecture applicative
:toc:
:sectnumlevels: 3
:sectnums:
:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://gitlab.com/bflorat/modele-da/raw/develop/diagrams

== Introduction

Ce document fourni le point de vue applicatif. 
Se référer aux volets joints pour les points de vue infrastructure, sécurité et développement. 

=== Documentation de Référence
Mentionner ici les documents d'architecture de référence (mutualisés). Ce dossier ne doit en aucun cas reprendre leur contenu sous peine de devenir rapidement obsolète et inmaintenable.

.Références documentaires
[cols="e,e,e,e"]
|===
|N°|Version|Titre/URL du document|Détail

|1|2.0.4|XX_Urba_POS.pdf|POS du SI|
|===

== Non statué
=== Points soumis à étude complémentaire
.Points soumis à étude complémentaire
[cols="e,e,e,e,e"]
|====
|ID|Détail|Statut|Porteur du sujet  | Échéance

|EA1
|EN_ATTENTE
|En fonction de l’avancement du projet Y, ce composant pourrait appeler les services de ce dernier ou ceux de l’ancien composant Z
|Projet Y
|AVANT 2040

|====


=== Hypothèses
.Hypothèses
[cols="e,e"]
|====
|ID|Détail

|HA1
|Même si la décision de généralisation de l'annuaire centralisé n'est pas totalement entérinée, l’application s’appuiera dessus et non sur un annuaire local.
|====

== Contexte général

=== Objectifs

[TIP]
Décrire succinctement le projet et en rappeler les objectifs. Mettre en évidence ceux qui sont structurants pour l’architecture.

====
Exemple 1 : Cette application doit permettre la dématérialisation des factures reçues de nos fournisseurs et une consultation aisée de ces documents par les services comptables.
====
====
Exemple 2 : ce projet constitue en la réécriture en technologies Web de l’application Cobol X.
====
====
Exemple 3: l’ application X est l’un des composants principaux du programme Y. Il s’adosse sur les référentiels Personne et Facturation pour enrichir le CMS en données clients temps réel.
====

=== Existant
[TIP]
Si ce document présente un projet de refonte ou migration, décrire a minima l'application existante. Ne pas reprendre la documentation, y faire simplement référence et pointer vers son éventuel dossier d'architecture. Mentionner néanmoins toute information ayant un impact fort sur la migration ou la conception du nouveau projet.
====
Exemple 1 : L'application VENIR2 est une application Client-Server en FORMS 4 pointant vers une base Oracle 9i. Son dossier d'architecture est donné en [REFxyz].
====
====
Exemple 2 : L'application existante se base et alimente un annuaire LDAP pour ses autorisations. Le nouveau projet devant fonctionner un temps avec l'ancienne, il convient de prendre en compte les accès concurrents et la cohérence du LDAP pendant la période de tuilage.
====

=== Positionnement dans le SI
[TIP] 
Si le SI est urbanisé, reprendre le plan d’occupation au sol et préciser le bloc concerné 

=== Acteurs
====  Vision d’ensemble
[TIP]
====
Proposer ici un schéma (UML 2 use case ou C4 context de préférence) présentant de façon exhaustive les acteurs de l’application. Un acteur peut être un humain ou un système informatique. Rester macro sur les use-cases (ce document n'est pas une spécification fonctionnelle générale) mais lister les acteurs de façon exhaustive et donner une première information sur la fréquence d'appels et la taille de la population.

Bien différentier les acteurs internes et externes. On entend par ‘internes’ les acteurs appartenant à l’organisation. Il peut s’agir d'humains ou de composants applicatifs.

La liste d'acteurs peut être donnée dans des tableaux ou dans un diagramme.
====
image::{gitplant}/utilisateurs.puml[Diagramme vision d'ensemble]


== Principes de l'architecture applicative
[TIP]
======
L'architecture applicative décrit le système d’information en composants communicants (sans donner le détail interne de ces composants, ce qui est du ressort de l'architecture logicielle).

Rappeler ici :

 * Le type d'architecture (client-serveur, Web monolithique, SOA, micro-service...).
 * Les grands flux entre les composants ou entre les applications dans le cas des monolithes.
 * Les principes d'architecture applicative (normalement définis par les urbanistes).
 * D'éventuelles dérogations.

======

====
Exemple 1 : les appels inter-services sont interdits sauf les appels de services à un service de nomenclature.
====
====
Exemple 2 : tous les batchs doivent pouvoir fonctionner en concurrence des IHM sans verrouillage des ressources.
====
====
Exemple 3 : les services ne peuvent être appelés directement. Les appels se feront obligatoirement via une route exposée au niveau du bus d'entreprise qui appellera à son tour le service. Il est alors possible de contrôler, prioriser, orchestrer ou piloter les appels.
====
====
Exemple 4 : Les composants de cette application suivent l'architecture SOA telle que définie dans le document de référence X.
====

== Architecture applicative générale
[TIP]
====
Présenter ici l'application dans son ensemble (sans détailler ses sous-composants) en relation avec les autres applications du SI. Présenter également les macro-données échangées ou stockées. 

Le choix de la représentation est libre mais un diagramme C4 de containers ou un diagramme de composant UML2 semble le plus adapté.

Numéroter les étapes par ordre chronologique assure une meilleure compréhension du schéma. Grouper les sous étapes par la notation x, x.y, x.y.z, ...

Ne pas faire figurer les nombreux systèmes d'infrastructure (serveur SMTP, dispositif de sécurité, reverse proxy, annuaires LDAP, ...) qui sont du domaine de l'architecture technique. Mentionner en revanche les éventuels bus d'entreprise qui ont un rôle applicatif (orchestration de service par exemple).
====

====
Exemple: MesInfosEnLigne permet à une entreprise de récupérer par mail un document récapitulant toutes les informations dont l’administration dispose sur elle. L'administration peut compléter ses données par celles d'une autre administration.
====

image::{gitplant}/archi-applicative-generale.puml[Diagramme architecture applicative générale]

== Architecture applicative détaillée
[TIP]
Détailler ici tous les composants de l’application, leurs flux entre eux et avec les autres applications du SI.

=== Schéma global
[TIP]
====
Proposer un ou plusieurs schémas (de préférence des diagrammes C4 de type composant ou diagramme UML2 de composant) avec flux numérotés. 

Idéalement, le schéma tiendra sur une page A4 et sera autoporteur. Il devrait devenir un des artefacts documentaire les plus importants et figurer dans la war room d'un projet agile ou être imprimé par chaque développeur. Il doit donc être particulièrement fiable et clair.

Si l'application est particulièrement complexe, faire un schéma par chaîne de liaison.

Utiliser comme ID des flux une simple séquence non signifiante (1, 2, ..., n).
Les flux sont logiques et non techniques (par exemple, on peut représenter un flux HTTP direct entre deux composants alors qu'en réalité, il passe par un répartiteur de charge intermédiaire). Ce niveau de détail sera donné dans le volet infrastructure. 
====

====
Exemple d'application :

image::{gitplant}/archi-applicative-detaille.puml[Diagramme architecture applicative détaillée]

====
=== Matrice des flux applicatifs
[TIP]
Lister et détailler les flux dans un tableau de flux intégrant pour chaque flux : un ID, une origine, une destination, un protocole, un attribut synchrone/asynchrone, un attribut lecture/écriture, une description.

.Matrice des flux applicatifs
|====
|ID|De|vers|Protocole | Réseau|Description|Type de transmission|Lecture/Écriture

|1|Navigateur de l'usager|ihm-miel|HTTPS| Internet|Interactions avec l'IHM JSF2|Synchrone|Lecture
|2|ihm-miel|file-demandes|JMS/IIOP|LAN|Production de la demande de renseignement|Synchrone|Écriture
|3|batch-traiter-demandes|file-demandes|JMS/IIOP|LAN|Consommation de la demande de renseignement au fil de l'eau (intervalles de l'ordre de 5 mins)|Synchrone|Écriture
|4|batch-traiter-demandes|service-miel|SOAP/HTTP|LAN|Appel du service de demande de notre application|Synchrone|Lecture
|5|service-miel|service-ref-entreprise-details|REST/HTTPS|LAN|Appel sécurité pour récupérer les données de l'entreprise dans le référentiel|Synchrone|Lecture
|6|service-ref-entreprise-details|Base bdd-ref-entreprises|JDBC/pg|LAN|Accès à la base|Synchrone|Lecture
|7|service-miel|service-complements|SOAP/HTTPS|WAN sur LS privée|Appel sécurisé TLS (double certificats X509) à la administration B pour récupérer les données complémentaires de l'entreprise|Synchrone|Lecture
|8|service-miel|service-compo-pdf|SOAP/HTTP|LAN|Appel au service de composition JasperReport de PDF|Synchrone|Lecture
|9|service-miel|serveur-mail|SMTP|LAN|Envoi du mail avec le PDF en PJ|Synchrone|Écriture
|10|service-miel|Base bdd-miel|JDBC/PG|LAN|Historisation de la demande|Synchrone|Écriture
|====

== Détails
[TIP]
Au besoin, clarifier certains points de façon textuelle si le schéma et la table des flux applicatifs ne suffit pas (ne pas reprendre tout le schéma, il s'agit de points précis uniquement).

====
Exemple : Le courriel ne devra pas dépasser 5 Mo pour passer les filtres du relais X. Il convient de prévoir un contrôle dans service-miel en retour du service de composition.
====

