# Vue développement
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

*Dernière modification* : {docdate} 

*Date de la dernière revue globale* : _<Faire régulièrement des revues complètes de la vue (au moins une fois par an tant que le projet est actif) et mentionner la date ici>_

*Statut du document* :  _<Indiquer ici le statut de la vue, par exemple 'DRAFT', 'FINALISÉ',...>_

//🏷{"id": "84c5d434-ea70-41fc-92bc-53a40ab29025", "labels": ["contexte"]}
## Introduction

La vue développement décrit le code à produire et les méthodes pour l'écrire.

Les autres vues du dossier sont accessibles link:./README.adoc[d'ici].

Le glossaire du projet est disponible link:glossaire.adoc[ici]. Nous ne reprendrons pas ici les termes fonctionnels ou techniques déjà définis.

//🏷{"id": "712fc07b-76ba-4093-bbf8-cceeaa903e64", "labels": ["references"]}
### Documentation de Référence

[TIP]
Mentionner ici les documents d'architecture de référence (mutualisés). Ce document ne doit pas reprendre leur contenu sous peine de devenir rapidement obsolète et immaintenable.

.Références documentaires développement
[cols="1e,1e,4e,4e"]
|====
|N°|Version|Titre/URL du document|Détail

|1|1.0|https://references.modernisation.gouv.fr/rgaa-accessibilite/#menu
|RGAA

|====

//🏷{"id": "fa1ed85e-92d0-4aa9-9421-dcf267d0cf0e", "labels": ["contexte","incertitudes"]}
## Non statué

//🏷{"id": "b3592a4d-d0df-4f87-8416-97cfb287cd08", "labels": []}
### Points nécessitant une étude complémentaire

.Points nécessitant une étude complémentaire
[cols="e,e,e,e,e"]
|====
|ID|Détail|Statut|Porteur du sujet  | Échéance

|ED1
|Le choix Angular ou React.JS pour le frontend est encore soumis à étude. Ceci n’impacte pas la partie back des services REST
|EN_COURS
|Equipe méthodes et outils
|AVANT 2040

|====

//🏷{"id": "fb0b1a28-1c08-4c0b-bb38-1cae99a46818", "labels": []}
### Hypothèses

.Hypothèses
[cols="1e,4e"]
|====
|ID|Détail

|HD1
|Même si ce point n’est pas encore totalement validé, l’application nécessitera un JRE 21+ pour tirer partie de librairies et frameworks Java indispensables au projet.
|====


//🏷{"id": "84cd4aed-36c0-4564-8354-29a7de004923", "labels": ["niveau_detail::general", "contraintes"]}
## Contraintes

[TIP]
====
Lister ici les contraintes relatives à l'architecture logicielle, ceci inclut de façon non-exhaustive :

* L'obligation d'utiliser un framework ou une filière technologique précise ;
* Les budgets disponibles pour les licences ou les frais de développement ;
* L'outillage (IDE, etc.) ;
* L'intégration continue ;
* Les normes et niveaux de qualité de code applicables ;
* Les tests (taux de couverture, répartition par type de test, etc.).

====
====
Exemple 1 : La couverture de code devra être d'au moins 60%.
====
====
Exemple 2 : Le module devra se baser sur le framework Hibernate pour la persistance.
====
====
Exemple 3 : l'application sera construite, testée et déployée en continu à chaque push via la plateforme Gitlab-CI.
====

//🏷{"id": "8d79cc07-e094-4863-8bb8-0a3ca317743d", "labels": ["niveau_detail::general","exigences"]}
## Exigences non fonctionnelles

[TIP]
====
Contrairement aux contraintes qui fixent le cadre auquel toute application devait se conformer, les exigences non fonctionnelles sont données par les porteurs du projet (Product Owner/MOA en général). Prévoir des interviews pour les déterminer. Si certaines exigences ne sont pas réalistes, le mentionner dans le référentiel des points à statuer.
====

//🏷{"id": "48bb8b97-2e97-4515-bf3b-95864f85e4e9", "labels": ["ihm"]}
### Accessibilité

[TIP]
====
Cette application doit-elle être accessible aux non/mal voyants ? malentendants ? 

Si oui, quel niveau d’accessibilité ? 
Se référer de préférence au Référentiel Général d’Accessibilité (https://references.modernisation.gouv.fr/rgaa-accessibilite/#menu[RGAA]) qui préconise un niveau WCAG 2.0 AA : 

Il existe d’autres normes d’accessibilité (WCAG, AccessiWeb, etc.) . Attention à correctement évaluer le niveau visé (ni sur-qualité, ni sous-qualité) :

* Atteindre un niveau d’accessibilité très élevé peut être coûteux et contraignant technologiquement. Il demande également de bonnes compétences (accessibilité, HTML5/CSS3 en particulier) et des profils rares.
* La loi est de plus en plus stricte pour les administrations qui doivent respecter un niveau d’accessibilité suffisant (loi  n°2005-102 du 11 février 2005 pour l’égalité des droits et des chances, la participation et la citoyenneté des personnes handicapées). « Tous les sites publics européens doivent atteindre le double A (AA) du W3C/WAI ».
====

//🏷{"id": "b098d142-655e-4521-9d4f-2c2ea8eceb45", "labels": ["ihm"]}
### Ergonomie

//🏷{"id": "3c031334-5598-4817-87b4-dec34ce8389b", "labels": ["niveau_detail::détaillé"]}
#### Charte ergonomique

[TIP]
====
En général, on se réfère ici à la charte ergonomique de l’organisme. Lister néanmoins d’éventuelles spécificités. Ne pas reprendre les contraintes d’accessibilité listées plus haut.
====
 
//🏷{"id": "90b4af62-df5b-485e-87c4-7dd0b21d0464", "labels": ["niveau_detail::approfondi"]}
#### Spécificités sur les widgets

[TIP]
====
Des comportements ergonomiques très précis peuvent impacter assez fortement l’architecture et imposer une librairie de composants graphiques ou une autre. Il est fortement déconseillé de personnaliser des librairies existantes (coût de maintenance très élevé, grande complexité). Bien choisir sa librairie ou restreindre ses besoins.
====
====
Exemple 1 : les tableaux devront être triables suivant plusieurs colonnes.
====
====
Exemple 2 : de nombreux écrans seront pourvus d’accordéons
====

//🏷{"id": "1cacea74-bede-43b3-93a5-804fd60ff4fb", "labels": ["niveau_detail::approfondi"]}
#### Polices de caractère

[TIP]
====
Décrire ici les polices de caractère à utiliser pour les pages Web, les applications ou les documents composés.

Le choix des polices suit des contraintes de licences. Afin d'assurer une sécurité juridique au projet, attention aux polices commerciales soumises à royalties (en particulier les polices appartenant à Microsoft comme Times New Roman, Courier, Verdana, Arial) et qui ne permettent pas de produire gratuitement des documents sans passer par leurs éditeurs (Word, etc.). 

Voir par exemple la police https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/la-typographie[Marianne] préconisée par le gouvernement en tant que police à chasse variable.

Redhat propose quatre familles de polices https://fr.wikipedia.org/wiki/Liberation_(police_d%27%C3%A9criture)[Liberation Mono] en licence Open Source sécurisante sur un plan juridique et compatible métriquement avec le Monotype, le Courrier New, l'Arial et le Times New Roman. 
====

//🏷{"id": "cfd3435f-d888-43e3-a634-35c3d5d92cb4", "labels": ["niveau::intermédiaire", "niveau_detail::approfondi"]}
#### Site Web adaptatif

[TIP]
====
Lister les contraintes d’affichage multi-support. Utiliser quand c'est possible les frameworks modernes (type Angular, Vue.js ou React.js). Il existe plusieurs niveaux d’adaptation des pages Web :

* Statique (largeur de page fixe).
* Dynamique (redimensionnement automatique, les tailles sont exprimées en %).
* Adaptatif (les distances sont exprimées en unités dont la taille dépend du support).
* Responsive (le contenu et son agencement dépend du support).

WARNING: Un design responsive vient avec ses contraintes (duplication de code CSS, augmentation du volume du site à télécharger par le client, complexité, plus de tests end-to-end à prévoir, etc.). 
====

//🏷{"id": "30cc6226-2213-4351-83aa-a4905c5d4baa", "labels": ["niveau::avancé", "niveau_detail::approfondi"]}
#### Progressive Web Apps (PWA)

[TIP]
====
Spécifier si l'application est progressive. Les applications PWA sont des applications Web HTML5 possédant tous les attributs des applications natives (mode déconnecté, rapide, adaptatif, accessible depuis l'OS, etc.) 
====
====
Exemple : L'application X sera totalement PWA. Des tests devront démonter que le site continuer à fonctionner sans réseau et que les pages se chargent en moins de 5 secs en 4G. 
====

//🏷{"id": "67ff8381-8145-4dc4-bd15-cfec867dc8b5", "labels": []}
#### Navigateurs supportés

[TIP]
====
Préciser quels sont les navigateurs supportés si votre projet contient une IHM Web. 

Lorsqu'on s'adresse à un public dont on ne gère pas le parc de navigateurs (comme un site Web sur Internet), la meilleure option pour rendre les choses intelligibles et expliciter les enjeux est de négocier avec les parties prenantes du projet un pourcentage de public supporté en se basant sur des https://gs.statcounter.com/[statistiques]. Par exemple : "Support de 95 % des navigateurs à date d'aujourd'hui".
====

WARNING: Supporter d’anciens navigateur (IE en particulier) peut engendrer des surcoûts rédhibitoires et des risques sur la sécurité. Dans tous les cas, il convient d’évaluer les surcoûts de tester sur plusieurs plate-formes. Il existe de bons outils (payants) comme Litmus ou EmailOnAcid permettant de générer un rendu des sites Web et des courriels HTML sur une combinatoire d’OS / type de lecteur (PC/tablette/mobile) /navigateur très vaste (de l’ordre de 50).  Ce type de site est incontournable pour une application grand public.

====
Exemple 1 : L’application intranet X devra fonctionner sur les navigateurs qualifiés en interne (cf norme xyz)
====
====
Exemple 2 : L’application Y étant une application internet visant le public le plus large possible, y compris des terminaux de pays en voie de développement. Il devra supporter Firefox 3+, Chrome 49+, IE 8+, Opera 6+.
====
====
Exemple 3 : L’application Z vise le public le plus large et doté de systèmes raisonnablement anciens et devra donc supporter : Firefox 135+, Chrome 126+, Safari 5+, Opera 20+, Edge.
====

//🏷{"id": "39318743-8131-4d46-9354-c64804066ae8", "labels": ["niveau::avancé", "niveau_detail::approfondi"]}
#### Mode déconnecté

[TIP]
====
Préciser si l'application doit pouvoir continuer à fonctionner sans accès à Internet ou au LAN (courant pour les applications utilisées par les professionnels en déplacement par exemple). 

Il peut s’agir de clients lourds classiques (Java, Kotlin, JS, C++, etc.) possédant leur base locale pouvant être synchronisée de retour au bureau. Il peut aussi s'agir d'applications PWA (voir plus haut) utilisant un service worker pour les resources statiques et du stockage navigateur (local storage, base de données IndexedDB).
====
====
Exemple 1 : L'application sera développée en Kotlin Jetpack Compose avec stockage local basé sur une base H2 synchronisées avec la base commune par appels REST.
====
====
Exemple 2 : L'application mobile sera en mode PWA, entièrement écrite en HTML5 avec local storage pour stocker les données de la journée dans le navigateur.
====

//🏷{"id": "fbe627e5-be3f-41ec-9a2a-c43bd3587c6e", "labels": []}
#### Internationalisation (i18n)

[TIP]
====
Préciser les contraintes de l’ application en terme d’i18n : localisation des libellés, direction du texte, mise en page adaptable, code couleur spécifique, format de dates, devises, affichage des séparateurs décimaux, etc.
====
====
Exemple 1 : L’IHM X sera traduite en 25 langues dont certaines langues asiatiques et l’arabe.
====
====
Exemple 2 : les formats de dates et autres champs de saisie devront être parfaitement localisés pour un confort maximal de l’utilisateur. 
====



//🏷{"id": "8c3bc449-1b44-44cf-82a1-f26cdbf258af", "labels": ["ihm"]}
### Exigences de SEO

[TIP]
====
Le SEO (Search engine optimization) concerne la visibilité d'un site Web au travers des moteurs de recherche (comme Google Search, Bing ou Quant).
====
====
Exemple 1 :  Aucune indexation nécessaire ni désirée (site interne)
====
====
Exemple 2 : Les pages statiques du site devront suivre les bonnes pratiques SEO pour optimiser sa visibilité.
====

//🏷{"id": "c8e58371-6bea-48e2-ab0e-989fec63e0ee", "labels": []}
### Exigences d'écoconception

[TIP]
====
L'écoconception consiste à limiter l'impact environnemental des logiciels et matériels utilisés par l’application. Les exigences dans ce domaine s'expriment généralement en kilowattheures (KWH) ou équivalent CO2.

A noter que la loi française (voir loi https://ecoresponsable.numerique.gouv.fr/publications/guide-pratique-achats-numeriques-responsables/demarche-numerique-responsable/que-prevoit-la-loi/[du n°2020-105 du 10 février 2020, ou loi AGEC]) exige de réduire le gaspillage lié au numérique, notamment concernant l'obsolescence logicielle (art. 27). 

Lister ici les exigences d'écoconception portant sur les logiciels.

====
====
Exemple : Les émissions cumulées du service A ne devrait pas dépasser 100KgCO2/an.    
====

//🏷{"id": "2c0aa24a-24b8-4272-8787-b5e5207785fb", "labels": ["niveau_detail::general","solution"]}
## Architecture cible

//🏷{"id": "50b4ef16-e558-4604-9b17-b90e68da6337", "labels": []}
### Pile logicielle

//🏷{"id": "16dc549a-4b87-428e-b59d-4c0af1e720db", "labels": ["niveau::avancé"]}
#### Filière technique retenue

[TIP]
====
Détailler les technologies choisies parmi les technologies au catalogue de l’organisation. S’il existe des écarts avec le catalogue, le préciser et le justifier.
====
====
Exemple : cette application est de profil P3 : "Application Web Spring" avec utilisation exceptionnelle de la librairie JasperReport.
====
====
Exemple : Utilisation de Rust à titre expérimental au sein de l'organisation. Validé en commité architecture le …
====

//🏷{"id": "e9b08c72-a836-48ad-9255-e2977a09f290", "labels": []}
#### Dépendances

[TIP]
====
Lister ici pour chaque module les principales librairies et frameworks utilisés ainsi que leur version. Ne pas lister les librairies fournies au runtime par les serveurs d'application ou les frameworks. Inutile de trop détailler, donner uniquement les dépendances structurantes.
====
====
Exemple :

.Exemple de pile logicielle
[cols="1e,4e,1e"]
|====
|Dépendance|Rôle|Version 

|Framework React.js
|Framework JS de présentation
|19

|JasperReport
|Éditique transactionnelle, composition des factures au format PDF
|7.0.0
|====
====

//🏷{"id": "ec64dc5b-cdc1-4ab3-ae41-ac3c1c3ad9e7", "labels": ["niveau::intermédiaire"], link_to=["d6e3eb12-371b-4c26-b538-9fea2051bfed"]}
### Performances

[TIP]
====
Même si des campagnes de performance sont prévues, l'expérience montre que la plupart des problèmes de performance peuvent être détectés dès le développement.
Il est donc important que les développeurs profilent leur code, dès leur poste de travail (à prévoir dans le Definition Of Done du projet). Il ne sera pas possible de détecter tous les problèmes (scalabilité, concurrence, robustesse, tuning des caches, etc.) mais c'est le cas de la plupart des problèmes de temps de réponse. Il est également souvent possible de simuler de la concurrence et de la charge. Nous présentons ici quelques pistes très basiques et à la portée de tout développeur.

Coté Frontend :

* Limiter la complexité des CSS (sélecteurs ou fonctions en particulier) ;
* Utiliser un profiler (comme celui de Chrome ou Firefox) ;
* Privilégier les appels asynchrones quand c'est possible.
* …

Coté Backend :

* S'assurer que la pagination serveur va bien jusqu'à la base de donnée (en PostgreSQL, utiliser `FETCH FIRST x ROWS ONLY`.
* Ne pas mettre en place de contraintes inutiles en base de données.
* Limiter le nombre de jointures et les relations many-to-many.
* Dans des cas de grosses volumétries, étudier les solutions de partitionnement de tables.
* Ne pas oublier d'ajouter tous les index nécessaires, utiliser l'analyse du plan d'exécution pour vérifier qu'il n'y a pas de full scans.
* Attention aux fonctions SQL qui 'cassent' les index (comme  `UPPER()`). Privilégier les traitements coté code backend si possible ou prévoir des index de fonctions correspondants.
* Activer les journaux de requêtes (exemple Hibernate : `org.hibernate.SQL=DEBUG`,`-Dhibernate.generate_statistics=true`) et vérifier les requêtes SQL et leur nombre (pour détecter en particulier le problème du https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem-in-orm-object-relational-mapping[SELECT N+1], très courant).
* Disposer même sur poste de travail d'un jeu de donnée minimal (une centaine d'enregistrement).
* Vérifier avec un profiler (comme JVisualVM en Java) la consommation mémoire pour détecter les fuites ou les surconsommations.
* Vérifier qu'il n'y a pas de fuite de threads ou de deadlocks en comptant le nombre de threads actifs sur une période suffisamment longue (une nuit complète par exemple).
* Stresser les API _a minima_ (avec des injecteurs comme JMeter ou K6) et via une rampe progressive.
* Traquer les IO (des milliers de fois plus lents que des accès mémoire).
* …

Frontend et backend : 

* Toute ressource (taille de chaîne, nombre d'appel sur une durée, etc.) doit systématiquement être bornée par une limite (pas d'« open bar »).
* Vérifier que la taille des requêtes HTTP reste en dessous de quelques dizaines de Kio (hors GET sur fichiers). Utiliser la <<Tri et Pagination,pagination cliente et serveur>>.
* Traquer le bavardage réseau : grouper les requêtes quand possible (il faut trouver un compromis avec la règle précédente). S'aider de la règle ‘I’ de SOLID (Interface Segregation).
* Prévoir des endpoints multivalués (exemple: `GET /personnes?list=id1,id2,…`) pour récupérer plusieurs éléments à la fois
(doit se concrétiser par un seul `SELECT WHERE .. IN` dans la requête finale, pas une boucle dans le code !)

====

WARNING: Ne pas tomber à l'inverse dans l'optimisation prématurée "source de tous les problèmes" selon Donald Knuth. Écrire le code le plus simple possible et suivre un bon design, ne l'optimiser qu’ensuite. 
N'optimiser que si cela vaut le coût (loi de Pareto). Commencer par les optimisations les plus significatives (top 10) et ne pas perdre son temps à grappiller des microsecondes voire nanosecondes.

//🏷{"id": "cacf4bd8-9e8a-449c-af31-1fd27169a685", "labels": ["niveau::intermédiaire",  "niveau_detail::détaillé"]}
### Spécificités d’usine logicielle

[TIP]
====
Sans reprendre le fonctionnement de la plate-forme d’Intégration Continue de l'organisation (CI), préciser si ce projet nécessite une configuration particulière.
====
====
Exemple : Les jobs Jenkins produiront le logiciel sous forme de conteneurs Docker/OCI si  tous les TU sont passants. Les tests d'intégration seront ensuite exécutés sur ce conteneur. Si tous les tests d’intégration et BDD sont passants, l'image Docker/OCI est livrée dans Nexus.
====

//🏷{"id": "11f66697-ac3a-40f0-903a-cc8202b7315e", "labels": []}
### Bonnes pratiques

[TIP]
====
Lister les bonnes pratiques (blueprints) applicables. Éviter les bonnes pratiques 'maison' mais privilégier celles qui viennent de la communauté et sont donc éprouvées et déjà connus des développeuses et développeurs. Idéalement, il ne devrait y avoir ici que les liens vers des ressources externes.
====
====
Exemple : Suivre les recommendations de https://www.restapitutorial.com/[ce tutoriel] pour la conception d'API Restful.
====

//🏷{"id": "4cfc1f5e-bf4b-4c33-b718-83ca90974090", "labels": ["niveau_detail::détaillé"]}
### Normes de développement et qualimétrie

[TIP] 
==== 
Rendre explicite les règles et le niveau de qualité requis pour le code 
==== 
==== 
Exemple 1 : Les règles de qualité à utiliser pour le code seront https://rules.sonarsource.com/java[les règles standards SonarQube pour Java]. 
==== 
==== 
Exemple 2 : Le niveau de qualité exigé correspond au https://docs.sonarqube.org/6.7/QualityGates.html[Quality Gate SonarQube] recommandé : 

* 80% de couverture minimum sur le nouveau code.
* 3 % max de lignes dupliquées 
* Niveau A en Maintenabily, Relability et Security 
==== 

====
Exemple 3 : Quelle langue utilisée pour le code ? français pour les termes fonctionnels (il est impératif d'utiliser les termes métiers comme préconisé par le DDD) et l'anglais pour les termes techniques génériques.
====

//🏷{"id": "bbe62a07-d42a-4495-8d23-4d0ea23d19e6", "labels": ["level::intermediate", "project_size::large"]}
### Patterns notables

[TIP]
====
Préciser si ce projet a mis en œuvre des patterns structurants (GoF, JEE ou autres). Inutile de reprendre les patterns déjà supportés par les langages ou les serveurs d'application (par exemple, l'IoC dans un serveur JEE).
====
====
Exemple 1 : pour traiter l'explosion combinatoire des contrats possibles et éviter de multiplier les niveaux d'héritage, nous utiliserons massivement la pattern décorateur [GoF] dont voici un exemple d’utilisation : <schéma>.
====

//🏷{"id": "99e519d3-e8cf-4b3c-8e87-e06a1bf675af", "labels": ["level::intermediate", "project_size::large"]}
### Spécificités des tests 

[TIP] 
==== 
Une méthodologie ou une technologie particulière est-elle en jeu dans ce projet ? Quelle est la stratégie de tests ? 
==== 
==== 
Exemple 1 : ce projet sera couvert en plus des TU et tests d’intégration car des tests d'acceptance BDD (Behavioral Driven Development) en technologie Spock. 
==== 
==== 
Exemple 2 : ce projet sera développé en TDD (test first) 
==== 
==== 

Exemple 3 : Types de tests 

.Types de tests 
[cols='2s,1,1,1,1,4a'] 
|==== 
|Type de test | Temps à investir | Manuel ou automatisé ? | Type de module ciblé | Taux de Couverture visée | Détail 

|TU 
|Très élevé 
|Automatisé 
|Backend et Frontend  
|env. 80% 
|Format BDD : spécifications de comportements des classes et méthodes 

|Spécifications exécutables 
|Très élevé 
|Automatisé 
|API  
|env. 100% pour les classes du domaine 
|Mode bouchonné.  

|Tests de contrats 
|Faible 
|Automatisé 
|Liens UI/API 
|env. 100% du code appelant coté UI et des contrôleurs Spring coté API 
|Teste la non régression des échanges lors de l'appel des opérations des API REST (principe CDC=Consumer-Driven Contract) via les outils Pact et pact-react-consumer. 

|Tests d'architecture 
|Très faible 
|Automatisé 
|API et batchs 
|N/A, 100% du code est validé par l'outil 
|En particulier, ces tests simples à écrire vérifieront le respect des règles de l'architecture hexagonale. Utilisation du framework de test ArchUnit. 

|TI (tests d'intégration) 
|Faible 
|Automatisé 
|Test appelant des systèmes externes (bases de données, API, etc.) 
|50 à 60% 
|Chaque TI ne doit tester qu'un seul système externe à la fois 

|E2E (tests bout en bout) 
|Faible 
|Automatisé 
|UI 
|30%, cas nominaux (happy path) 
|Ecrits en Playright, Cypress ou technologie similaire. Ils seront limités à un rôle de smoke tests (détection de problèmes grossiers). Ces tests ne seront pas bouchonnés mais seront effectués sur chaîne de liaison instanciée de bout en bout. Pour éviter le travail inutile, ces tests seront faits au niveau de features entières, pas forcément à chaque sprint. Ces tests feront office également de tests système puisqu'ils solliciteront un maximum de modules débouchonnés. 

|Tests de performance 
|Faible (hors campagnes de performance dédiées) 
|Automatisé 
|API critiques 
|20% 
|Possiblement automatisés en CI en DEV mais également lancé manuellement par les développeurs 

|Tests d'accessibilité 
|Moyenne 
|Automatisé + manuel 
|UI 
|50%  
|Tests Axe-Core lancés en CI à compléter d'un audit manuel 

|Tests de sécurité 
|Moyenne 
|Manuel 
|Tous 
|Faible, uniquement sur les fonctions sensibles 
|Audit à prévoir 

|Tests système 
|Faible 
|Manuels 
|UI et batchs 
|10%  
|Tests menés par l'équipe de développement couvrant des scénarios fonctionnels complets. Le but  
est ici de tester le fonctionnement de l'ensemble des modules (ce qui n'est pas automatisable) et de  
détecter un maximum de bugs avant les tests d'UAT. 

|Tests UAT (acceptation) 
|Moyenne 
|Manuels 
|UI, batchs lancé à la main 
|de 30% à 80% selon le nombre de scénarios prévus  
|Tests menés en recette par des utilisateurs finaux sur environnement non bouchonné avec des cahiers de tests. Tests d'acceptance de bout n bout (on suit un cahier de tests avec les cas nominaux), Tests exploratoires (on tente toutes les combinatoires possibles avec un guidage minimal dans le cahier de test). Utilisation de l'outil Squash pour le suivi.
|==== 
==== 

NOTE: Pour un projet d'envergure, la stratégie de test fait en général l'objet d'un document propre. Une stratégie standard peut également être définie au niveau du SI. 

//🏷{"id": "6ff8aacb-5020-4ade-a10d-3dce3898276b", "labels": ["level::intermediate", "detail_level::detailed"],"link_to": ["c8e58371-6bea-48e2-ab0e-989fec63e0ee"]}
=== Éco-conception

[TIP]
====
Lister ici les mesures logicielles permettant de répondre aux exigences d'écoconception listées plus haut. Les réponses à ces problématiques sont souvent les mêmes que celles aux exigences de performance (temps de réponse en particulier). Dans ce cas, y faire simplement référence. Néanmoins, les analyses et solutions d'écoconception peuvent être spécifiques à ce thème.

Un point de départ intéressant pour manipuler l'impact carbone peut être la formule SCI (Software Carbone Intensity):

```
SCI = ((E * I)) + M) par R
```

Avec: 

* E (kWh) : L'énergie totale consommé par le logiciel ; 
* I (gCO2/kWh), la quantité de carbone émis par kwH ;
* M (gCO2) : l'empreinte carbone du hardware ;
* R: la quantité de référence (ex: par utilisateur, par appareil, ...)

Quelques pistes d’amélioration énergétique du projet :

* Utiliser des profilers ou des outils de développement intégrés dans les navigateurs (comme Google Dev Tools) pour analyser la consommation de ressources (nombre, durée et taille des requêtes).
* Pour les apps, utiliser des outils de supervision de la consommation de batterie comme Battery Historian.
* Utiliser la suite d'analyse spécialisée Greenspector.
* Mesurer la consommation électrique des systèmes avec les sondes PowerAPI2 (développé par l'INRIA et l'université Lille 1).
* Mesurer la taille des images et les réduire (sans perte) avec des outils comme pngcrush, OptiPNG, pngrewrite ou ImageMagick.
* Optimiser la consommation mémoire et CPU des applications, tuner le GC pour une application Java.
* Faire du lazy loading pour le chargement des ressources occasionnelles.
* Limiter les résultats retournés de la base de données (pagination).
* Grouper les traitements de masse dans des batchs qui seront plus efficaces (lots).
====
====
Exemple 1 : le processus Vite de construction de l'application appliquera une réduction de taille des images via le plugin vite-imagetools.
====
====
Exemple 2 : des tests de robustesse courant sur plusieurs jours seront effectués sur l’application mobile après chaque optimisation pour évaluer la consommation énergétique de l'application.
====
====
Exemple 3 : Les campagnes de performance intégreront une analyse fine de la consommation de bande passante et en cycles CPU même si les exigences en temps de réponses sont couvertes, ceci pour identifier des optimisations permettant de répondre aux exigences d'éco-conception si elles ne sont pas atteintes.
====
====
Exemple 4 : Pour une exigence de 100 KgCO2/an maximum emit par le service en ligne A : on utilise 20% d'un serveur physique. On estime l'intensité carbone du serveur hors fonctionnement à 1.5TCO2 sur tout son cycle de vie de 10 ans (donc 30 kgCO2/an au prorata du service A).

En utilisant la formule SCI (voir plus haut), et pour une consommation totale du serveur de 800W et 20K appels par heure en moyenne, et une électricité française d'intensité carbone de 63g/KWH, on ne doit pas dépasser E=1111 KWH/an, soit 6.34 mWH/appel.

====

//🏷{"id": "bb5d8145-8519-4516-98a9-fc089f758d9c", "labels": ["level::intermediate", "detail_level::detailed"]}
### Gestion de la robustesse

//🏷{"id": "a7bacacc-de70-48e5-8563-6a0b6d7b31a2", "labels": ["level::advanced"]}
#### Gestion des transactions

[TIP]
====
Lister ici les décisions prises concernant la gestion des transactions. Ceci est surtout utile pour un système distribué. Quelques exemples de problématiques : 

* Autorise-t-on les mises jours sur de multiples modules lors d'une même requête ? 
* Si oui, assurons nous le caractère ACID du tout (via le mode XA par exemple) ? 
* Quel moteur transactionnel utilisons nous ? 
* Quel niveau d'isolation transactionnelle (read commited, uncommited, repeatable read, serializable) ?
* Si aucun moniteur transactionnel n'est utilisé (appel de plusieurs services REST en mise à jour par exemple), prévoit-t-on des transactions compensatoires en cas d'échec de l'une des mises à jours ? un pattern https://learn.microsoft.com/en-us/azure/architecture/patterns/saga[SAGA] ? des jobs de resynchronisation ? ...

====
====
Exemple : nos ressources n'étant pas transactionnelles (services REST), et voulant éviter de faire des transactions compensatoires, il est interdit d'appeler deux services en mise à jour de façon synchrone. Au besoin, nous utiliserons une file de messages pour effectuer des mises à jour au fil de l'eau.
====

//🏷{"id": "8bd70b17-0223-4aaf-97ac-a7284efe721f", "labels": ["level::intermediate", "detail_level::in-depth"]}
#### Gestion des sessions

[TIP]
====
Comment gère-t-on les sessions HTTP permettant de fournir un contexte d'exécution à un utilisateur (exemple: son panier d'achat) ? 

Notez que ceci est une surtout un problème pour les applications Web classiques dont la présentation est générée sur le serveur, pas pour les applications SPA (Single Page Application) qui gèrent toute la présentation et leur état en local dans le navigateur.

Les choix faits ici affecteront les link:vue-infrastructure.adoc[choix d'infrastructure]. Par exemple, si une session est requise et que l'infrastructure est en cluster, il faudra soit mettre en place de l'affinité de session sur les serveurs pour forcer chaque utilisateur à toujours arriver sur le même serveur disposant de ses données, soit de mettre en place un cache distribué permettant aux serveurs de partager les sessions de tous les utilisateurs (plus complexe et plus lourd).

Exemples de points à traiter :

* Quelles données doivent être conservées en session  ? (attention à la volumétrie, surtout si cache distribué)
* Le code doit-il être thread-safe (si le même utilisateur ouvre un autre onglet dans son navigateur par exemple) ?

====
====
Exemple : notre application JSF stockera en session HTTP uniquement son panier d'achat, pas les références produits
====

//🏷{"id": "4ffcfd1b-87c9-48d0-96d6-f3b3b817a869", "labels": []}
#### Gestion des erreurs

[TIP]
====
Comment gère-t-on les erreurs ? Exemples de points à traiter :

* Différencions-nous erreurs fonctionnelles (erreurs fonctionnelles prévues) et techniques ? Prévoir un diagramme de classe.
* Comment logue t-on les erreurs ? quel niveau de log ? 
* Où sont attrapées les exceptions ? au plus tôt ou en début d'appel de façon centralisée ?
* Utilise-t-on les exceptions standards du langage (ex: `IOException`, etc.) ou notre propre jeu d'exceptions ?
* La liste des erreurs est-elle consolidée ? documentée ? 
* Affecte-t-on des codes erreur ?
* Affiche-on les stack-traces complètes ? si oui, coté serveur et coté client ?
* Gère-t-on les rejeux ? si oui, espace-t-on les rejeux ? de façon aléatoire (jitter) ? exponentielle (exponential backoff) ?
* Comment gère-t-on les timeouts ?
* Comment gérons-nous les rejets fonctionnels? (c.-à-d. que faire des demandes partielles ou erronées?) 

====
====
Exemple : les erreurs techniques (imprévues) comme le timeout à un appel de service REST sont catchées au plus haut niveau de l'application (via un ErrorHandler). Toutes ses informations sont loguées avec la stack-trace complète mais l'appelant ne doit recupérer que le code erreur générique XYZ sans la stack-trace (pour raison de sécurité).
====

//🏷{"id": "7a33eb60-882d-4095-bde2-9a477cc27433", "labels": ["gui"]}
#### Gestion de la robustesse coté frontend

[TIP]
====

Tout comme le backend, le frontend requiert une robustesse importante, d'autant plus qu'il est en prise directe avec des utilisateurs finaux. 

Entre autres :

* Penser à interdire les doubles soumissions (double appel au backend si on double-clic sur un bouton). Ceci n'exclut pas de procéder à des contrôles de durcissement coté backend.

* Afin d'éviter des problèmes subtils (surtout en cas d'utilisation de stockage navigateur comme les local/session storage), penser à empêcher l'ouverture d'une même application Web dans plusieurs fenêtres ou onglets du navigateur. En cas de tentative, afficher un message d'erreur dans les fenêtres surnuméraires.

* Toujours vérifier la comptabilité du navigateur, même en environnement contrôlé. En cas de tentative d'ouverture d'une page par un navigateur non supporté, afficher un message d'erreur explicite à l'écran.
====

====
Exemple 1 : Si l'application est ouverte avec IE, un message d'erreur doit inviter l'utilisateur à utiliser un navigateur supporté.
====

====
Exemple 2 : Tous les boutons de l'application devront interdire la double soumission en désactivant temporairement les bouton sur événement.
====

//🏷{"id": "d101d1ee-8ec7-48dd-b733-ebba345c656d", "labels": ["detail_level::detailed"]}
### Gestion de la configuration

[TIP]
====
Comment configure-t-on l'application ? Exemples de points à traiter :

* Quelles sont les variables incluses dans le package final de façon statique ?
* Quels sont les paramètres modifiables au runtime ? 
* Mon application est-elle paramétrable via feature flags pour des raisons de canary testing par exemple ? si oui, comment je le gère dans le code ?
* Sous quelle forme les paramètres sont-ils injectés dans l'application (variable d'environnement ? fichier .properties, base de données, etc.) ? 
* L'application accepte-elle une modification du paramétrage à chaud ?
* Décrire le système de configuration

====
====
Exemple (application déployées dans Kubernetes) : 

La configuration sera injectée au lancement (non modifiable à chaud) via des variables d'environnements fournies dans le descripteur de déploiement Kubernetes.
====

//🏷{"id": "01a81b2c-1dc0-4563-a2e2-5c5248086499", "labels": ["level::advanced", "detail_level::in-depth"]}
### Politique de gestion des branches

[TIP]
====
Quels sont les workflows de branche à prévoir ? git-flow ? TBD (Trunked-based Development) ? autre ?
====

====
Exemple : 

* La politique générale adoptée est la https://trunkbaseddevelopment.com/[TBD] (Trunk-Based Development)
* La branche principale est `develop`. Il s'agit d'une branche protégée vers laquelle il n'est pas possible pousser de commits.
* Tout commit devra faire l'objet d'une Merge Request avant intégration dans `develop`. Les critères de qualité (évalués de façon automatique lors de l'intégration continue) devront être atteints pour que le commit soit intégré.
* Chaque fonctionnalité, refactoring significatif ou bugfix sera donc réalisé sur une branche topic dédiée.
* Une branche de maintenance sera tirée sur chaque tag de version x.y. Seuls les bugfixs seront mergés dans les branches de maintenance depuis `develop` via des `cherry-pick`.
====

//🏷{"id": "35b97569-e671-40c3-809c-ffcb5d1af383", "labels": ["detail_level::detailed"]}
### Versioning

[TIP]
====
Que versionne-t-on et quel système de version utilise-t-on ?
====

====
Exemple: 

* D'une façon générale, toute ressource non dérivée (source, outil, script de ci-cd, template, DDL de base de données, etc.) doit être versionnée.
* Les modules seront versionnés suivant la numérotation `x.y.z` (`<majeur).<évolution>.<fix>`)
* Les librairies seront versionnées suivant la même numérotation que les modules mais la valeur `x` sera incrémentée lors de toute montée de version cassant la compatibilité ascendante (principe du Semantic Versioning).
* La version logique globale du projet sera : `<lot>.<no sprint>.<déploiement>`

====

//🏷{"id": "79682de3-09b7-46f1-8354-9371295d18a8", "labels": ["level::intermediate",  "detail_level::in-depth"]}
### Gestion de la concurrence

[TIP]
====
Comment gère-t-on les accès concurrents ? Exemples de points à traiter :

* Quel scope pour les objets (si utilisation d'un moteur IoC) ?
* Les objets doivent-il être thread-safe ?
* Quelles méthodes doivent être synchronisées ?
* Risques de race condition ? de famine ? de dead locks ?

====
====
Exemple  (Spring MVC) : Tous les controllers seront en scope singleton et ne doivent donc en aucun cas stocker d'état dans leurs attributs pour éviter des accès concurrents.
====

//🏷{"id": "856b9e7b-3305-48c3-bb99-798cf409181d", "labels": ["level::intermediate", "detail_level::detailed"]}
### Encodage 

[TIP] 
==== 
Quelles sont les règles concernant l'encodage des chaînes de caractères ? Ceci est un problème récurrent dans les SI (qui n'a jamais observé d'accents corrompus sous forme de carrés ?). Ce problème est pourtant relativement simple à résoudre. Voir les exemples ci-dessous pour des exemples de dispositifs effectifs. 
==== 

==== 
Exemple 1 : Le seul encodage autorisé dans tous les modules et composants d'infrastructure est l'`UTF-8`. L'utilisation des encodages `ISO-8859-1`, `CP-1252` ou de tout autre est formellement proscrit. Ceci comprend le paramétrage des serveurs d'application (Node, Tomcat, etc.), des sources, des fichiers de configuration, des bases de données et des fichiers. 

NOTE: Dans certains cas, nous n’avons pas la main sur la lecture des `.properties` (depuis un framework par exemple), il n’est alors pas possible de forcer un encodage en `UTF-8`. Il faut alors s'assurer qu'on spécifie l'encodage effectif dans l'outil ou le code qui le lit.

==== 
==== 
Exemple 2 : Si un système externe impose d'envoyer ou de recevoir des chaînes de caractères dans un encodage autre que le `UTF-8` (exemple : un service REST qui renvoi des données en `ISO-8859-1`) et qu’il n’est pas possible de modifier le contrat, il est impératif de traduire au sein d'une couche anti-corruption les chaînes de caractères et ceci au plus tôt, dès l'appel. De plus, il ne faut jamais persister dans nos systèmes une donnée dans un encodage non `UTF-8`. 
==== 

//🏷{"id": "5885803d-2d3d-4e19-af30-40e904e9fb6d", "labels": ["level::intermediate", "detail_level::detailed"]}
### Fuseaux horaires 

[TIP] 
==== 
Comment gère-t-on le stockage des dates ? Ceci, comme la gestion de l'encodage est un problème récurrent (décalage d'un jour, bugs lors des changements d'heure d'été/hiver, etc.). Pour éviter les problèmes, suivre la norme https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] ("Time zones in ISO 8601 are represented as local time (with the location unspecified), as UTC, or as an offset from UTC." [Wikipedia]). 
==== 

==== 
Exemple 1 : Les heures ne seront jamais stockées sans fuseau horaire. En base, on utilisera des timestamps avec timezone (`timestamptz`) et en Java ou JS, des objets intégrant le fuseau horaire de façon explicite (ex: `Instant` et pas `LocalDateTime` en java) ou des epochs. La précision sera au moins de la milliseconde. 
==== 
==== 
Exemple 2 : Les dates et date-heures seront stockées en base de données comme epoch millis au format entier long. Dans le cas des dates, on stockera l'epoch millis à `12:00 UTC` (et pas `00:00`, trop proche du jour précédent, risque de bug). 
==== 

//🏷{"id": "96ec879c-3ce3-4e48-a3f9-84590c281fd4", "labels": ["detail_level::detailed"]}
### Gestion des journaux

NOTE: Les aspects d'infrastructure de journaux sont détaillés dans link:./vue-infrastructure.adoc#_journaux[la vue infrastructure].

[TIP]
====
Fournir ici les règles générales concernant les journaux (logs) : leur niveau de prolixité et le volume qu'ils représentent.
Penser à l'exploitation des journaux, surtout coté serveur. Se demander s'il sera possible d'en tirer profit en cas d'erreur en production au milieu de Mio voire Gio d'autres journaux et de nombreux threads écrivant en parallèle.
====

//🏷{"id": "cad3fb2c-5047-4025-892f-3180e74579c8", "labels": ["detail_level::in-depth"]}
#### Règles générales

====
Exemple 1 : 

* Ne pas laisser de journaux de développement dans le code (exemple : `console.out("entrée dans méthode x")` ou `e.printStackTrace()`)
* Penser à utiliser des chaînes de caractère discriminantes (exemple : code erreur) pour faciliter le filtrage dans l'outil de recherche de journaux.
* Toujours fournir des identifiants d'entités permettant de retrouver l'objet concerné 
* Utiliser des identifiant de corrélation entre tiers (exemple : id de traitement générée coté client en JS, passée au serveur)
* Eviter les calculs coûteux (exemple: beaucoup de concaténations) en utilisant des placeholders (La chaine de caractère à loguer finale n'est effectivement construite que si le niveau de prolixité requis est utilisé). Exemple Logback : 
```
log.info("Problème sur le dossier {} de l'utilisateur {}",dossier.getId(), utilisateur.getId());
```
====

//🏷{"id": "992c0bb3-83bc-4598-84ff-150a67df3324", "labels": ["detail_level::in-depth"]}
#### Niveaux et quantité de journaux
[TIP]
====
Expliquer quand et quoi loguer de sorte à produire des journaux exploitables en production.
====

====
Exemple :   

.Niveaux journaux
[cols='1,3,1,1']
|====
|Niveau de gravité |Contexte d'utilisation | Volume indicatif | Environnement 

|DEBUG
|En environnement de développement, il permet d'afficher les valeurs de variables, E/S de méthodes etc.. 
|Max quelques Mio / minute
|DEV, Recette. Interdit en PROD sauf demande expresse du projet

|INFO
|Début/fin d'un batch ou d'un appel, chargement d'une nouvelle propriété. Peut être utilisé sous forme condensée pour les appels de service (logging d'un appel et de son contexte). C'est le niveau de prolixité utilisé pour la métrologie.
|Max 10 journaux / sec, quelques Kio / minute
|Tous

|WARN
|Tous les messages d'avertissement sur les informations fonctionnelles inattendues
|Pas de limites mais ne pas en abuser et y positionner un maximum de détail de contexte
|Tous

|ERROR
|Toutes les erreurs qui n'empêchent pas à l'application de fonctionner.
|Pas de limites. Positionner un maximum de détail de contexte
|Tous

|FATAL
|Toutes les erreurs bloquantes pour l'application (problème d'accès BDD, HTTP  404 ou 500). Positionner un maximum de détail de contexte. Penser à bien logger ces erreurs sur un appender console au cas où l'écriture sur FS serait impossible (disque plein). Penser que lors d'une erreur fatale, l'écriture même du log est sujette à caution (par exemple en cas de dépassement mémoire).
|Pas de limites. 
|Tous
|====

====
 
//🏷{"id": "f2e9066c-18d9-4234-b37c-27d342b1c99e", "labels": ["level::intermediate", "project_size::large", "detail_level::detailed"]} 
### Outils d'administration

[TIP]
====
L'application doit-elle fournir des services d’administration ? Il est fortement conseillé (c'est le facteur 12 des https://12factor.net/[Twelve factors d'Heroku]) d'intégrer le code d'administration directement avec le code métier.

Exemples de points à traiter :

* Dois-je fournir un moyen de purger des données, journaux, caches, etc. ? 
(on appelle quelque fois ce type de service un 'traitement interne')    
* Dois-je fournir des indicateurs applicatifs de supervision ? (nombre de dossiers consultés, etc.) ?
* Dois-je fournir des outils de migration ?

====
====
Exemple : Le service `/interne/maj_v2` effectuera une montée de version du modèle de donnée vers la V2
====

//🏷{"id": "ef97a533-5fc7-4999-87fc-def24074746c", "labels": ["level::intermediate", "detail_level::detailed"]}
### Tri et Pagination

[TIP]
====
Il est nécessaire de conserver une bonne fluidité de récupération des données en lot. La pagination permet de limiter le bavardage entre les clients (IHM et batchs) et les API. Décrire ici les dispositifs de pagination mis en oeuvre coté client et coté serveur.
====

====
Exemple 1 (Coté serveur) 

* Les requêtes en sortie de l'API sont systématiquement triées selon un ordre ascendant (le défaut) ou descendant. De plus, il sera possible de choisir le champ sur lequel se fait le tri via un autre query param.
* Afin de limiter le nombre de requêtes à destination de l'API, celle-ci retourne un nombre limité d'éléments (ce nombre sera paramétrable suivant la taille des éléments individuels). Il s'agit du query param `range` contenant le numéro de la page à récupérer + le nombre d'éléments de la page. Chaque API proposera une valeur par défaut (de l'ordre d'une centaine).
====

====
Exemple 2 (Coté client) 

* Le tri doit s'appliquer sur l'ensemble des éléments en base, pas seulement sur les éléments de la dernière requête retournée par le serveur. 
* Les éléments retournés seront affichés dans les tableaux par blocs (taille paramétrable d’une taille indicative de l'ordre de 20 éléments). 
====

//🏷{"id": "4af6fb38-c84a-456f-b043-32abeb6e7798", "labels": ["level::intermediate" "detail_level::detailed"]}
### Provisioning et mises à jour des DDL

[TIP]
====
Décrire comment les DDL (structures de tables en base de données) et les données initiales (comme des nomenclatures) seront gérées puis mis à jour.
====

====
Exemple : Nous utiliserons Liquibase embarqué dans les livrables pour créer et mettre à jour les DDL de la base. Il n'y aura donc pas de scripts SQL à lancer, les requêtes nécessaires seront effectuées directement par l'application lors de son démarrage.
====

//🏷{"id": "201fca5f-50af-41f9-ab97-60b2f7abddc6", "labels": ["level::intermediate",  "detail_level::detailed"], link_to=["fbe627e5-be3f-41ec-9a2a-c43bd3587c6e"]}
### Gestion de l'internationalisation
[TIP]
====
Décrire comment vous répondez aux exigences d'internationalisation exprimées plus haut.
====

====
Exemple : La gestion des dates, pluriels et nombres se fera via le https://icu.unicode.org/[standard ICU] et la librairie JS http://messageformat.github.io/messageformat/[messageformat]. 
====
