# Vue sécurité
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Sommaire

[PRE-FILLED]
====
*Dernière modification* : _{docdate}_

*Date de la dernière revue globale* : 

*Statut du document* :  

====

TIP: Faire régulièrement des revues complètes de la vue (au moins une fois par an tant que le projet est actif) et mentionner la date ici

TIP: Indiquer le statut de la vue, par exemple 'DRAFT', 'FINALISÉ',...

//🏷{"id": "a08e807e-1e9b-4752-a5b8-372a40665c49", "labels": ["contexte"]}
## Introduction

La vue sécurité décrit l'ensemble des dispositifs mis en œuvre pour empêcher l'utilisation non-autorisée, le mauvais usage, la modification illégitime ou le détournement des modules applicatifs.

Les autres vues du dossier sont accessibles link:./README.adoc[d'ici].

Le glossaire du projet est disponible link:glossaire.adoc[ici]. Nous ne reprendrons pas ici les termes fonctionnels ou techniques déjà définis.

[TIP]
La disponibilité est traitée dans la vue infrastructure.

//🏷{"id": "cd8c64f1-d216-4b24-946c-175455e824a7", "labels": ["contexte","references"]}
### Documentation de Référence

[TIP]
====
Mentionner ici les documents d'architecture de référence (mutualisés). Ce document ne doit pas reprendre leur contenu sous peine de devenir rapidement obsolète et non maintenable.
====

[PRE-FILLED]
====
[cols="1,1,4,4"]
|===
|N°|Version|Titre/URL du document| Détail

|1
|
|
|
|
|===
====

//🏷{"id": "ea245600-dbd6-4f56-a58c-8c77556643ad", "labels": ["contexte","incertitude"]}
## Non statué

//🏷{"id": "a058d388-72e1-4136-8659-7a9db1c1a340", "labels": []}
### Points nécessitant une étude complémentaire

=====
Exemple : 

[cols="1e,3e,1e,1e,2e"]
|===
|ID|Détail|Statut|Porteur du sujet | Échéance

|ES1
|Il conviendra de valider que les dispositifs anti-CSRF mis en place résolvent également les failles liées au couplage TLS + compression (type CRIME ou BREACH). 
|EN_COURS
|Équipe sécurité
|AVANT 2040

|===
=====

[PRE-FILLED]
====
[cols="1,3,1,1,2"]
|===
|ID|Détail|Statut|Porteur du sujet | Échéance

| 
| 
| 
| 
| 
|===
====


//🏷{"id": "68a4f41c-1139-4cdd-bb9e-e15667f47fd9", "labels": []}
### Hypothèses

[TIP]
====
Donner ici les éventuelles hypothèses structurantes

Exemple:

[cols="e,6e"]
|===
|ID|Détail

|HS1
|La solution SAML actuellement en place dans l’organisation ne permet pas de répondre aux besoins d’authentification exprimés pour cette application Internet. Une solution OpenID Connect sera proposée. 
|===
====

[PRE-FILLED]
====
[cols="1,6"]
|===
|ID|Détail

| 
| 
|===
====

//🏷{"id": "53ae9c06-1846-4dd2-ab55-f4a784c6a676", "labels": ["niveau_detail::général", "contrainte"]}
## Contraintes

[TIP]
====
Lister ici les **contraintes de sécurité** applicables à l'architecture, incluant notamment :

- **Isolation des modules** au sein de zones réseaux sécurisées (_DMZ, pare-feux, reverse proxy, segmentation réseau, etc._).
- **Normes et politiques applicables** (_ex. : politiques de mots de passe, exigences de chiffrement, MFA, conformité aux standards de sécurité_).
- **Contraintes légales et réglementaires** (_ex. : conformité RGPD, exigences sectorielles spécifiques_).
- **Restrictions d'accès** entre les différentes zones et systèmes.

====
====
Exemple 1 : La politique de gestion des mots de passe devra se conformer à la norme `XYZ`, incluant une complexité minimale et un renouvellement périodique.
====
====
Exemple 2 : Il est formellement interdit à un module de la **zone Internet** d'accéder directement à la **zone Intranet**.
====
====
Exemple 3 : En application du **RGPD**, les données utilisateur devront être chiffrées **au repos et en transit** avec **AES-256 et TLS 1.3**.
====

//🏷{"id": "4882e5b9-c250-4079-8b24-04996016606d", "labels": ["niveau_detail::général", "exigence"]}
## Exigences

[TIP]
====
Présenter ici les **exigences**, *pas les dispositifs y répondant*. Ceux-ci seront détaillés au chapitre 3.

Pour les projets particulièrement sensibles, prévoir un **dossier d’analyse de risque**. Pour cela, utiliser par exemple la méthode https://www.ssi.gouv.fr/guide/la-methode-ebios-risk-manager-le-guide/[EBIOS Risk Manager] (_Expression des Besoins et Identification des Objectifs de Sécurité_).
====

//🏷{"id": "323d4c77-810a-4015-bc1a-11da07e24f3b", "labels": []}
### Exigences d'intégrité

[TIP]
====
L’intégrité concerne la **justesse, la durabilité et le niveau de confiance** des données de l’application.

Garantir l’intégrité des données signifie s’assurer qu’elles **ne peuvent être altérées ou supprimées** de manière involontaire (_ex. : crash disque, corruption logicielle, bug applicatif_) ou volontaire (_ex. : attaque "man-in-the-middle", élévation de privilèges, sabotage interne_).

⚠ **Ne pas multiplier inutilement les classes de données**. Une unique classification pour toute l’application est souvent suffisante.

Exemple : 

[cols='2e,1e,1e,1e,1e']
|===
|Classe de données |Non intègre [small]#(Les erreurs d'intégrité sont tolérées)# |Détectable [small]#(Les erreurs sont identifiées rapidement)# |Maîtrisé [small]#(Les erreurs sont corrigées)# |Intègre [small]#(Aucune altération n’est tolérée)#

|**Données de la base métier** | | | | X
|**Données archivées** | | X | |
|**Données statistiques agrégées** | | | X |
|**Silo NoSQL des données Big Data (avant consolidation)** | X | | |
|**Code source de l’application** | | | | X
|**Documents officiels générés (ex. : avis d’imposition PDF)** | | | | X
|===

Exemples de dispositifs associés selon le niveau d’intégrité requis :

- **Détectable** → Logs d’accès et vérification des empreintes numériques (hashes).
- **Maîtrisé** → Rétention des versions, auditabilité, correction automatique des erreurs détectées.
- **Intègre** → Chiffrement, signatures numériques, réplication synchrone, stockage immuable (WORM).
====

[PRE-FILLED]
====
[cols='2,1,1,1,1']
|===
|Classe de données |Non intègre [small]#(Les erreurs d'intégrité sont tolérées)# |Détectable [small]#(Les erreurs sont identifiées rapidement)# |Maîtrisé [small]#(Les erreurs sont corrigées)# |Intègre [small]#(Aucune altération n’est tolérée)#

| 
| 
| 
| 
| 

|===
====


//🏷{"id": "acfa846e-0ed7-4f41-a593-f4ee29e94efd", "labels": []}
### Exigences de confidentialité

[TIP]
====
La confidentialité est la garantie que l’information **n’est accessible qu’aux personnes autorisées** (définition ISO 27018).

**Bonnes pratiques** :  

- Ne pas multiplier inutilement les classes de données. Une seule classification peut suffire pour l’ensemble de l’application.
- S’assurer que les niveaux de confidentialité sont **cohérents avec les exigences légales et contractuelles**.

Exemple : 

[cols="e,e,e,e,e"]
|===
|Classe de données |Public [small]#(Donnée accessible à tous sans restriction)# |Limité [small]#(Accessible uniquement aux personnes habilitées)# |Réservé [small]#(Restreint au personnel interne autorisé)# |Privé [small]#(Accès strictement individuel)#

|**Contenu éditorial**  
| X | | | 

|**Données de profil utilisateur**  
| | X | | 

|**Historique du compte**  
| | | X | 

|**Logs techniques des activités**  
| | | X | 

|**Données RH (ex. : aides sociales aux employés)**  
| | | | X
|===

**Exemples d’applications des niveaux de confidentialité** :

- **Public** → Pages web accessibles sans connexion.
- **Limité** → Informations réservées aux utilisateurs authentifiés (ex : tableau de bord d’un SaaS).
- **Réservé** → Données internes sensibles (ex : logs système non accessibles aux clients).
- **Privé** → Données personnelles visibles uniquement par l’utilisateur concerné (ex : fiche de paie).
====

[PRE-FILLED]
====
[cols="1,1,1,1,1"]
|===
|Classe de données |Public [small]#(Donnée accessible à tous sans restriction)# |Limité [small]#(Accessible uniquement aux personnes habilitées)# |Réservé [small]#(Restreint au personnel interne autorisé)# |Privé [small]#(Accès strictement individuel)#

| 
| 
|
|
|
|===

====

//🏷{"id": "94c138c1-3e8b-4eaf-8926-b5b9bfa6a86b", "labels": []}
### Exigences d'identification

[TIP]
====
L’identification permet d'**attribuer un identifiant unique** à chaque utilisateur, afin de le différencier des autres.  

**Attention :**  L’identification **ne garantit pas** que l’utilisateur est bien celui qu’il prétend être. C’est le rôle de l’authentification (exemple : mot de passe, MFA…).

Exemple : 

[cols="1e,3e"]
|===
|Exigence |Description

|**Identifiant unique**  
| Chaque utilisateur doit avoir un identifiant **unique et non partageable**. Une adresse e-mail personnelle est un bon identifiant.

|**Validation de l'identité**  
| L'existence de l'identité d'un internaute doit être vérifiée avant tout appel de service.

|**Pérennité de l’identifiant**  
| Un identifiant ne doit **jamais être supprimé, modifié ou réutilisé**, même après la suppression d’un compte utilisateur.
|===

**Bonnes pratiques** :  

- **Privilégier des identifiants stables et uniques** (e-mail, numéro de client, UUID…).
- **Éviter les identifiants réattribuables** (exemple : ID numérique incrémental risquant d’être réutilisé après suppression d’un compte).
- **S'assurer que l'identifiant est cohérent dans tous les systèmes** où il est utilisé.
====

[PRE-FILLED]
====
[cols="1,3"]
|===
|Exigence |Description

|
| 

|===
====


//🏷{"id": "9d0646cd-3e3f-4878-96de-f215c9f20bdc", "labels": []}
### Exigences d'authentification

[TIP]
====
L’authentification vérifie qu’un utilisateur est bien celui qu’il prétend être, en validant son identité à l’aide d’un ou plusieurs facteurs de preuve.

⚠ **À ne pas confondre avec l’identification**, qui ne fait que distinguer un utilisateur d’un autre sans valider son identité.

**Cas particuliers :** 

- Les **comptes techniques** (ex: batchs, applications, API) nécessitent également une authentification (ex: comptes de service avec certificats ou clés SSH).
- Les **comptes à privilèges** (ex: `root` sur les serveurs, compte administrateur applicatif...). Ils peuvent être humains ou techniques mais peuvent lire/écrire/supprimer beaucoup de données ou réaliser des opérations irréversibles (blast radius large).
- L’**authentification initiale** (lors de l'inscription) est souvent plus stricte que les authentifications ultérieures.
- Une **authentification fédérée** permet de déléguer l’authentification à un fournisseur d’identité (SSO, OAuth2, SAML, etc.), voir la section suivante.

**Catégories de Facteurs d'Authentification**
[cols="1,3"]
|===
| Catégorie | Description

| Connaissance
| Quelque chose que l'utilisateur **connaît** (ex. : mot de passe, PIN).

| Possession
| Quelque chose que l'utilisateur **possède** (ex. : token, clé SSH, téléphone).

| Inhérence
| Quelque chose que l'utilisateur **est** (ex. : biométrie).

| Localisation
| Quelque chose lié à l'**emplacement** de l'utilisateur (ex. : IP, GPS).

| Comportement
| Quelque chose lié au **comportement** de l'utilisateur (ex. : rythme de frappe).
|===

**Facteurs d'Authentification : Tableau Comparatif**
[cols="1,1,1,2,2,1,1"]
|===
| Facteur d'authentification       | Catégorie       | Force | Description                                                                 | Faiblesses / Risques                                      | Cas d'usage recommandé                     | Norme associée

| Mot de passe                     | Connaissance   | Moyenne | Chaîne de caractères secrète connue de l'utilisateur.         | Vulnérable aux attaques par brute force, phishing, réutilisation. | Authentification de base (comptes personnels). | NIST SP 800-63B

| Phrase de passe                  | Connaissance   | Forte   | Série de mots faciles à retenir (ex: CorrectHorseBatteryStaple). | Moins vulnérable au brute force, mais nécessite une bonne mémorisation. | Comptes sensibles (banques, emails). | NIST SP 800-63B

| Clé publique SSH                 | Possession      | Forte   | Paire de clés asymétriques (publique/privée) pour l'authentification. | Perte/vol de la clé privée = accès compromis. Gestion complexe. | Accès aux serveurs (SSH, Git). | RFC 4251

| OTP par Token                    | Possession      | Forte   | Code à usage unique généré par un appareil physique (ex: RSA SecurID). | Dépendance matérielle (perte/vol). Coût. | Connexions sensibles (admin, VPN). | RFC 6238

| OTP par application (TOTP)       | Possession      | Forte   | Code temporaire généré par une app (Google Authenticator, Authy). | Dépend de l'appareil mobile. Risque si téléphone perdu. | Comptes en ligne (Google, AWS, banques). | RFC 6238

| Clé matérielle (YubiKey)         | Possession      | Très forte | Clé physique (USB/NFC) pour une authentification forte (FIDO2). | Coût (~50€). Nécessite un appareil compatible. | Accès admin, comptes sensibles, crypto-monnaies. | FIDO2

| Certificat numérique              | Possession      | Très forte | Certificat X.509 stocké sur une carte à puce ou un appareil. | Complexité de gestion (PKI). Coût. | Accès aux réseaux d'entreprise, VPN. | RFC 5280

| Biométrie                        | Inhérence       | Forte   | Empreinte digitale, reconnaissance faciale/voix/iris. | Faux positifs/négatifs. Problèmes de vie privée. | Déverrouillage d'appareils mobiles, accès physiques. | ISO/IEC 30107

| Reconnaissance comportementale    | Inhérence       | Moyenne | Analyse du rythme de frappe ou des mouvements de souris. | Peu fiable seul. Nécessite un apprentissage. | Détection de fraude (banques), accès internes. | ISO/IEC 24741

| Connaissance de données métier   | Connaissance   | Moyenne | Question basée sur des connaissances internes (ex: "Quel était le CA 2023 ?"). | Difficile à mémoriser. Peut être partagé. | Accès interne (RH, finance). | (Interne)

| E-mail avec lien de vérification | Possession      | Faible  | Lien envoyé par email pour vérifier l'identité. | Vulnérable au phishing et aux interceptations. | Réinitialisation de mot de passe. | (Aucune norme spécifique)

| Notification push                 | Possession      | Forte   | Notification envoyée à un appareil de confiance (ex: Duo Security, Okta Verify). | Dépend de la connexion réseau/mobile. | Applications mobiles (banques, réseaux sociaux). | (Propriétaire)

| Question secrète                   | Connaissance   | Faible  | Question personnelle (ex: "Nom de votre premier animal ?"). | Vulnérable aux devinettes et aux fuites. | Réinitialisation de compte. | (Déconseillé par NIST)

| Code PIN                          | Connaissance   | Faible  | Code numérique court (4-6 chiffres). | Limité et vulnérable au brute force. | Déverrouillage d'appareils (téléphone, carte bancaire). | PCI DSS

| Géolocalisation                   | Localisation    | Moyenne | Vérification de l'emplacement via IP/GPS. | Peut être contournée par VPN/proxy. | Accès à distance (VPN), restrictions géographiques. | (Aucune norme spécifique)

| Authentification par réseau      | Localisation    | Moyenne | Restriction aux IP/réseaux autorisés. | Restrictif (ex: seulement depuis le bureau). | Accès interne aux entreprises. | ISO/IEC 27001

| Authentification par appareil    | Possession      | Forte   | Appareil enregistré (ex: téléphone ou ordinateur de confiance). | Dépend de la possession de l'appareil. | Comptes Apple/Google, appareils mobiles. | (Propriétaire)

| Authentification continue        | Comportement    | Forte   | Vérification périodique (ex: biométrie toutes les 4h). | Complexité de mise en œuvre. | Environnements hautement sécurisés (banques, gouvernement). | NIST SP 800-63B
|===

**Recommandations par Cas d'Usage : **

**Accès Basique** (ex. : Site Web Public)
[cols="1,2"]
|===
| Facteur | Exemple

| Mot de passe
| `Tr0pF0rt!2024` (12+ caractères).

| OTP par email
| Lien de vérification envoyé par email.
|===

**Accès Sensible** (ex. : Compte Bancaire)
[cols="1,2"]
|===
| Facteur | Exemple

| Mot de passe
| Phrase de passe longue (`CorrectHorseBatteryStaple`).

| OTP par application (TOTP)
| Google Authenticator ou Authy.

| Biométrie
| Empreinte digitale ou reconnaissance faciale.
|===

**Accès Administrateur** (ex. : Serveur Cloud)
[cols="1,2"]
|===
| Facteur | Exemple

| Clé SSH + mot de passe
| Clé RSA 4096 bits + phrase de passe.

| OTP par token physique (YubiKey)
| YubiKey OTP ou FIDO2.

| Géolocalisation
| Restriction aux IP de l'entreprise.
|===

**Accès Interne** (ex. : Données RH)
[cols="1,2"]
|===
| Facteur | Exemple

| Certificat numérique
| Smart card ou certificat X.509.

| Connaissance de données métier
| "Quel était le chiffre d'affaires 2023 ?"

| Notification push
| Duo Security ou Microsoft Authenticator.
|===

**Accès à Distance** (ex. : VPN)
[cols="1,2"]
|===
| Facteur | Exemple

| OTP par application (TOTP)
| Authy ou FreeOTP.

| Géolocalisation
| Restriction aux pays autorisés.

| Clé matérielle (YubiKey)
| YubiKey + PIN.
|===

Le tableau ci-dessous indique les **facteurs d’authentification requis** selon le contexte d’utilisation (exemple) :  

[cols="e,e,e,e,e,e,e"]
|===
|Cas d'utilisation  |Mot de passe respectant la politique de sécurité  |Clé publique SSH connue  |OTP par Token  |Biométrie  |Connaissance de données métier  |E-mail avec lien de vérification  

|Utilisateur déjà inscrit  
|X|||||  

|Création d’un compte  
|||||XX|X  

|Modification du mot de passe  
|X|||||X  

|Accès aux journaux sécurisés  
||X||||  

|Ajout d’un bénéficiaire de virement  
|X||X|||  

|Connexion à l’application mobile Y  
||||X|||  
|===

**Bonnes pratiques** :  

* **MFA (Multi-Factor Authentication)** → éviter l’authentification uniquement par mot de passe.  
  Exiger **au minimum un second facteur** (OTP, clé FIDO2, biométrie, etc.).

* **Utiliser des standards éprouvés** → privilégier des protocoles reconnus tels que  
  **FIDO2**, **WebAuthn**, **TOTP**, **SAML 2.0**, **OpenID Connect**.

* **Sécuriser les comptes de service** → éviter les **mots de passe statiques**.  
  Préférer les **clés SSH**, **certificats client** ou **tokens JWT** à **durée de vie limitée**.

* **Prévoir la révocation et le renouvellement** → mettre en place des mécanismes pour  
  **révoquer et régénérer rapidement** un facteur d’authentification perdu, volé ou compromis.

* **Limiter les tentatives d’authentification** → bloquer temporairement le compte ou le sujet  
  lorsque le **seuil maximal d’échecs** est atteint, et **ajouter un délai croissant** entre les tentatives  
  pour limiter les attaques par **brute force**.

* **Mettre en place une rotation régulière des secrets** → renouveler périodiquement les clés, certificats  
  et tokens afin de réduire l’impact potentiel d’une compromission.

* **Utiliser une politique de mot de passe moderne** →  privilégier des phrases longues et faciles à retenir (plutôt que complexes), sans rotation forcée, sans caractères spéciaux forcés, vérifiées contre les mots de passe compromis (haveibeenpwned), avec copier/coller possibles (pour facilité l'utilisation de gestionnaires de mot de passe) et complétées par une authentification multifacteur (MFA). Référence: ANSSI, NIST SP 800-63B.

====

[PRE-FILLED]
====
[cols="1,1,1,1"]
|===
|Cas d'utilisation  | Facteur 1 | Facteur 2 | ...

| 
| 
| 
| 
|===

====

//🏷{"id": "f552f1e6-9aea-4866-8da1-e7ed676fd228", "labels": ["niveau::avancé", "niveau::avancé", "niveau_detail::détaillé"]}
### Exigences de fédération d’identité

[TIP]
====
La fédération d’identité permet à un utilisateur de **réutiliser son identité** (credentials) gérée par un **Identity Provider (IdP)** pour s’authentifier sur plusieurs systèmes indépendants.

Contrairement au **SSO (Single Sign-On)**, qui assure une connexion automatique sans nouvelle saisie des identifiants, la fédération **ne dispense pas** de l’authentification mais centralise la gestion des identités.

**Exemples courants :**  

- **France Connect** → Basé sur OpenID Connect, permet aux citoyens de se connecter aux services administratifs (DGFiP, CNAM…) avec un compte unique.  
- **"Se connecter avec [Google | Facebook | GitHub]”** → Implémenté via **OpenID Connect** ou **OAuth2**, permettant d’utiliser un compte tiers pour l’authentification sur une autre plateforme.

**Avantages de la fédération d’identité :**  

- **Simplifie la gestion des comptes** → Moins d’identifiants à mémoriser pour l’utilisateur.  
- **Réduit les coûts de maintenance** → Moins de réinitialisations de mot de passe et de gestion des utilisateurs.  
- **Améliore la sécurité** → Centralisation de l’authentification auprès d’un IdP de confiance, possibilité d’intégrer une authentification multi-facteurs (MFA).  
====

====
**Exemple d’application**

L’identification et l’authentification des utilisateurs seront externalisées à **Auth0**, un fournisseur d’identité (IdP) supportant **OIDC, SAML et OAuth2**.  

**Objectifs** :  

- **Centraliser la gestion des identités** et éviter la duplication des comptes utilisateurs.  
- **Réduire les coûts** de développement et d’exploitation liés à l’authentification.  
- **Améliorer la sécurité** en déléguant l’authentification à un IdP conforme aux normes de sécurité.
====

//🏷{"id": "400376ad-cc62-4ab3-8e96-5a9f9a954e49", "labels": ["niveau::avancé", "niveau::avancé"]}
### Exigences de SSO et SLO

[TIP]
====
Le **Single Sign-On (SSO)** permet à un utilisateur de s’authentifier une seule fois et d’accéder à plusieurs applications sans ressaisir ses identifiants.  
Le **Single Log-Out (SLO)** assure qu’une déconnexion depuis une application entraîne automatiquement la déconnexion de toutes les autres applications du même domaine de confiance.

**Points d’attention :**

- **Le SSO peut être complexe** à mettre en œuvre, surtout si l’infrastructure IdP (Identity Provider) n’est pas encore en place.
- **Les applications doivent être compatibles** avec le protocole choisi (SAML, OIDC, Kerberos…).
- **Le besoin métier doit être justifié** → Une application rarement utilisée ne nécessite pas forcément de SSO.
- **Risque sécurité** → Une **authentification faible** sur une application SSO met en péril tout le SI (ex. : un mot de passe faible compromet toutes les applications accessibles via SSO).

**Bonnes pratiques :**

- Définir des **périmètres de confiance** limités (ex. : SSO pour les applications internes uniquement).  
- Utiliser une **authentification forte** pour réduire les risques d’usurpation.  
- Gérer correctement les **sessions et expirations de jetons**.  
- Envisager **une authentification centralisée simple (LDAP, CAS)** si le SSO n’est pas justifié.  
====

====
**Exemple 1 : Pas de besoin de SSO**  
Le portail applicatif repose sur un framework JSR352 qui gère déjà l’authentification unique. Aucun besoin de SSO supplémentaire.
====
====
**Exemple 2 : Pas de SSO ni de SLO requis**  
L’application fonctionne de manière autonome et ne partage pas d’authentification avec d’autres services.
====
====
**Exemple 3 : SSO requis pour un environnement intranet**  

- Une fois authentifié sur l’une des applications de l’intranet, l’utilisateur ne doit **pas avoir à se reconnecter** sur les autres applications jusqu’à expiration de la session.  
- Une **déconnexion (SLO)** depuis une application doit entraîner **la déconnexion de toutes les autres applications** du domaine.  
- Le protocole choisi sera **OIDC avec un Identity Provider interne**.
====

//🏷{"id": "01404b83-f96f-4649-ace0-e5611601b830", "labels": ["niveau::avancé"]}
### Exigences de non-répudiation

[TIP]
====
La **non-répudiation** garantit qu’un utilisateur ou une organisation ne peut **nier** avoir réalisé une action donnée (signature, validation, transaction…).  
Elle repose généralement sur des mécanismes cryptographiques, notamment la **signature électronique** et l’horodatage sécurisé.

La signature numérique est reconnue légalement par **le texte n°2000-230 du 13 mars 2000 du code civil**, ainsi que par le **règlement eIDAS (UE 910/2014)** définissant plusieurs niveaux de signature :  
- **Simple** : Vérifie uniquement l’identité de l’émetteur.  
- **Avancée (AES)** : Liée de manière unique au signataire et protégée contre toute modification.  
- **Qualifiée (QES)** : Conforme aux normes les plus strictes, avec certificat qualifié et dispositif sécurisé.

**Cas d’usage typiques :**  

- Signature des **contrats et engagements légaux**.  
- Validation des **transactions financières sensibles**.  
- Soumission de **documents officiels** (déclarations fiscales, actes notariés…).
====

**Besoins de non-répudiation par cas d'usage**
[cols="e,e,e,e"]
|===
|Action ou document signé|Niveau de signature exigé|Origine du certificat client|Origine du certificat serveur

|Déclaration d’impôt sur le revenu (données X, Y et Z)
|Signature eIDAS qualifiée 
|PKI de l’administration fiscale
|Autorité de certification Verisign

|Contrat d’embauche électronique
|Signature eIDAS avancée
|PKI interne de l’entreprise
|PKI externe certifiée eIDAS

|Validation d’un paiement électronique
|Signature eIDAS avancée
|Certificat bancaire du client
|PKI du fournisseur de paiement (ex. : Visa, Mastercard)
|===

//🏷{"id": "958fcccc-60cb-4158-940f-279cd1d12c9b", "labels": []}
### Exigences d'anonymat et de respect de la vie privée

[TIP]
Lister les contraintes d’anonymat et de vie privée légale (exigée par le RGPD). Voir [3].

====
Exemple 1  : Aucune consolidation de donnée ne pourra être faite entre les données du domaine PERSONNE et du domaine SANTE.
====
====
Exemple 2  : Par soucis de confidentialité en cas d’intrusion informatique, certaines données des personnes seront expurgées avant réplication vers la zone publique : le taux de cholestérol et le poids.
====
====
Exemple 3 : aucune donnée raciale, politique, syndicales, religieuse ou d’orientation sexuelle ne pourra être stockée sous quelque forme que ce soit dans le SI.
====
====
Exemple 4 : Les données OpenData issues du domaine « logement » ne contiendront que des données consolidées de niveau commune, pas plus précise.
====
====
Exemple 5 : En application de la directive européenne « paquet telecom », un bandeau devra informer l’usager de la présence de cookies.
====
====
Exemple 6 : En application du RGPD, un consentement explicite des utilisateurs dans la conservation de leurs données personnelles de santé sera proposé.
====

//🏷{"id": "fcad5990-c241-4c88-b2c5-646602f8935a", "labels": ["niveau::intermédiaire"]}
### Exigences sur les autorisations

[TIP]
====
Une autorisation ("droit d'accès" ou "habilitation") permet de **contrôler l’accès** à une fonction applicative spécifique (également appelée **droit**, **privilège** ou **permission**) pour un utilisateur ou un groupe d’utilisateurs.

**Exemples de fonctions applicatives :**

- "Effectuer un virement interbancaire"
- "Consulter l’historique de son compte"
- "Supprimer un utilisateur"

⚠ Il est recommandé de **ne pas multiplier excessivement** les fonctions et les rôles afin d’éviter une explosion combinatoire et des coûts de gestion élevés.

**Bonnes pratiques pour simplifier la gestion des autorisations :**

- **Regrouper** les utilisateurs dans des **groupes** (ex: `G_chef_service`).
- **Associer** une liste de **fonctions** à un **rôle** (ex: `R_Administrateur`, `R_banquier_niv1`, `R_chef_service`).
- **Attribuer** les rôles aux **utilisateurs ou groupes** pour une meilleure factorisation.

**Modèle classique de gestion des autorisations :**  

image::diagrammes/roles.svg[Gestion classique des rôles]

**Pseudo-utilisateurs et rôles prédéfinis** :
Penser à spécifier les utilisateurs génériques tels que :

- **`@anonyme`** : utilisateurs non connectés.
- **`@connecte`** : utilisateurs authentifiés.

**Délégation d’autorisation (OAuth2, etc.) :**

Si l’application **délègue ou consomme** des autorisations via un **système externe (OAuth2, OpenID Connect, etc.)**, il est nécessaire de préciser :

- **L’application est-elle fournisseur ou consommatrice d’autorisations ?**
- **Quels types d’autorisations sont concernées ?**
====

====
Exemple 1 : Les utilisateurs **non connectés** auront **accès à tous les privilèges en lecture seule uniquement**.
====

====
Exemple 2 : L’application utilisera **une gestion des autorisations matricielle** basée sur une association **[rôles] → [groupes ou utilisateurs]**.  
Le détail des autorisations sera documenté dans les **SFD (Spécifications Fonctionnelles Détaillées)**.
====

**Exemple de matrice de rôles :**  
[cols="e,e,e,e"]
|===
| Groupe ou utilisateur | Rôle `suppression` | Rôle `administration` | Rôle `consultation données de base`

| Groupe `g_usagers`
|
|
| X

| Groupe `@anonyme`
|
|
|

| Groupe `g_admin`
| X
| X
| X

| Utilisateur `xyz`
| X
|
| X
|===

//🏷{"id": "e72e5ea5-5711-4665-8a91-76c63cbca2bc", "labels": ["niveau::intermédiaire"]}
### Exigences de traçabilité et d'auditabilité

[TIP]
====
Lister ici les besoins en **traçabilité et auditabilité** pour détecter et analyser :

* **Un usage abusif** des applications Back Office par des employés.
* **Des intrusions informatiques** ou tentatives de compromission.
* **Des modifications de données** nécessitant un suivi détaillé.

⚠ **Les traces sont des données nominatives et sensibles**. Elles doivent être protégées avec des **mécanismes de confidentialité** appropriés pour éviter tout abus.

**Différenciation des types de traces :**

- **Traces métier** : elles reflètent des actions de gestion complètes.  
  *Exemple* : `L’agent X a consulté le dossier de Mme Y le 2024-02-23 à 10:30`.  

- **Journaux applicatifs** : ils fournissent un niveau technique d’information.  
  *Exemple* : `[INFO] 2024-02-23 11:14 [Agent X] Appel du service "consulterDossier"`.

**Bonnes pratiques :**

- Pour les **données sensibles**, prévoir **une traçabilité à deux niveaux** (tracer aussi l’accès aux traces) pour limiter les abus hiérarchiques.  
- La **traçabilité des référentiels** (ex: base des personnes) doit inclure **une historisation complète**.  
- Concevoir un **MCD** (Modèle Conceptuel de Données) permettant de conserver **chaque modification** avec sa date de modification et sa date d’effet.  
====

====
**Exemple 1** : Pour le module X, **toute action métier** (consultation et mise à jour) devra générer une trace métier contenant _a minima_ :

- L'identité de l’agent.
- La date et l'heure.
- En cas de modification : **ancienne et nouvelle valeur**.
====

====
**Exemple 2** : Toute **intrusion dans le SI** devra être détectée dans la mesure du possible et remontée aux équipes de sécurité.
====

====
**Exemple 3** : Il doit être possible de **reconstituer l’historique** complet d’un dossier patient à **n’importe quelle date**.
====

### Données à conserver pour preuves
[TIP]
====
Exemple : 

[cols="e,e,e"]
|===
| Donnée | Objectif | Durée de rétention

| Log complet (IP, heure GMT, détail) des commandes passées sur le site
| Prouver que la commande a bien été passée
| 1 an 

| Date et contenu du mail de confirmation
| Prouver que le mail de confirmation a bien été envoyé 
| 2 ans

| Contrat d’assurance signé et numérisé en PDF
| Prouver que le contrat a bien été signé
| 5 ans

| Avis d’imposition primitif avec signature numérique
| Conserver le montant et la validation de l’impôt
| 5 ans
|===

====

[PRE-FILLED]
====
[cols="1,1,1"]
|===
| Donnée | Objectif | Durée de rétention

| 
| 
| 
|===
====

//🏷{"id": "d1f16239-18f7-4a4a-875e-34a587eb88b4", "labels": ["solution"]}
## Mesures de sécurité

//🏷{"id": "e60500e8-b4a3-471c-941c-8fd8c02c4da9", "labels": [], "link_to": ["323d4c77-810a-4015-bc1a-11da07e24f3b"]}
### Intégrité

[TIP]
====
Lister ici les mesures assurant le niveau d'intégrité demandé

Exemple: 

[cols="e,e,e"]
|===
| Classe de données | Niveau exigé | Mesures

| Données de la base métier
| Intègre
a|
* Utilisation du SGBDR **PostgreSQL** avec un niveau d’isolation transactionnelle **SERIALIZABLE**.
* Les entités seront référencées uniquement par des **ID techniques** issues de séquences PostgreSQL.
* Activation de la **journaling WAL** pour assurer la reprise en cas de crash.
* Vérification d'intégrité périodique avec `pg_checksums`.

| Données archivées
| Détecté
| Génération de checksums **SHA-256** des backups et validation lors des restaurations.

| Données calculées D1
| Maîtrisé
| Stockage d’un checksum **SHA1**, relance automatique du calcul par batch en cas de divergence dans un délai de **24h**.

| Silo NoSQL des données Big Data avant consolidation
| Non intègre
| Pas de mesure particulière, **pas de backup**, ces données sont temporaires et recalculables.

| Sources de l'application
| Intègre
a|
* Utilisation du **SCM Git** avec contrôle d’intégrité natif (hash SHA-1/SHA-256).
* Vérification des commits avec **GPG signing**.
* Stratégie de merge stricte (fast-forward only).

| Avis d’imposition PDF
| Intègre
a|
* **Signature numérique** du montant net, de la date et du nom via **PKCS#7 (RSA, SHA-256)**.
* **Horodatage qualifié** intégré à la signature (PAdES).
* Inclusion de la signature hexadécimale en **pied de page** du PDF pour vérification ultérieure.
|===

====

[PRE-FILLED]
====
[cols="1,1,1"]
|===
| Classe de données | Niveau exigé | Mesures

| 
| 
|
|===
====

//🏷{"id": "a64b5e5d-e4d4-4ed2-b425-19cd542fa58e", "labels": [], "link_to": ["acfa846e-0ed7-4f41-a593-f4ee29e94efd"]}
### Confidentialité

[TIP]
====
Lister ici les mesures assurant le niveau de confidentialité demandé.

Exemple:

[cols="e,e,e"]
|===
| Classe de données | Niveau exigé | Mesures

| Contenu éditorial
| Public
| Échanges sécurisés via **HTTPS** (TLS 1.2+), **pas d’authentification requise**.

| Profil du compte du site Web
| Limité
a|
* L’accès à ce contenu nécessite une **authentification réussie** par login/mot de passe.
* **Hash sécurisé des mots de passe** avec **Argon2id**.
* Utilisation de **JWT** pour les sessions avec expiration contrôlée.

| Historique du compte
| Réservé
a|
* L’accès est **réservé aux exploitants habilités**.
* Consultation uniquement via **requêtes PL/SQL sécurisées** exécutées avec un rôle limité en base de données.
* Activation du **Data Masking** pour les informations sensibles.

| Logs des activités de l’internaute
| Réservé
a|
* **Accès restreint** aux exploitants habilités via **SSH** et authentification forte (clé SSH + MFA).
* Rotation automatique des logs avec **logrotate**.
* Protection contre l’injection de logs (`log forging`).

| Données RH aides sociales aux employés
| Privé
a|
* **Chiffrement AES-256** en base sous forme de **BLOB**.
* Déchiffrement **côté client uniquement** via la librairie `forge.js` (JavaScript).
* Mot de passe complémentaire **non stocké côté serveur**, la perte du mot de passe rend les données irrécupérables.
* Les données modifiées sur le client sont **chiffrées avant envoi** et enregistrées dans le BLOB via le service REST X.
|===

⚠ **Confidentialité des données dérivées** :  

✔ **Chiffrement des backups** :  

- Utilisation de **Restic, Borg, Kopia** avec **chiffrement AES-GCM** et stockage sécurisé.  
- **Activation de S3 Object Lock (Compliance mode)** pour bloquer toute suppression accidentelle ou malveillante.

✔ **Chiffrement des données clientes pour les applications lourdes** :  

- **Chiffrement matériel** avec **SED (Self-Encrypting Drive)**.  
- **Chiffrement logiciel de partition** avec **LUKS (dm-crypt)** ou **BitLocker**.  
- **Chiffrement au niveau fichier** avec **dm-crypt**, **encfs** ou **Cryptomator**.
====

[PRE-FILLED]
====
[cols="1,1,1"]
|===
| Classe de données | Niveau exigé | Mesures

| 
| 
| 
|===
====

//🏷{"id": "3779a946-fc73-455b-8bab-3d5398ce0311", "labels": [], "link_to": ["94c138c1-3e8b-4eaf-8926-b5b9bfa6a86b"]}
### Identification

[TIP]
====
Décrire ici le mode d’identification des utilisateurs et des systèmes (batchs, API, services externes).  
Préciser les attributs d’identification et les mécanismes garantissant l’unicité et la persistance des identifiants.
====

====
Exemple 1 : L’identifiant des usagers sera l’attribut `uid` des DN `cn=XXX,ou=service1,dc=entreprise,dc=com` dans l’annuaire LDAP central.  
Un filtre sera également appliqué pour restreindre l'accès aux membres du groupe `ou=monapplication,dc=entreprise,dc=com`.
====
====
Exemple 2 : Pour éviter la réutilisation des identifiants de comptes supprimés, une table d’historique `historique_uid` sera ajoutée à la base de données et systématiquement interrogée avant toute création de nouveau compte.
====
====
Exemple 3 : Les comptes de service seront identifiés via une clé API unique stockée dans un **Vault sécurisé** et soumise à une rotation automatique tous les 6 mois.
====

//🏷{"id": "ac587042-7060-44cf-96aa-93fddadc15f5", "labels": [], "link_to": ["9d0646cd-3e3f-4878-96de-f215c9f20bdc"]}
### Authentification

[TIP]
====
Décrire ici les mécanismes d’authentification mis en place, y compris :  
- Le mode de stockage et de vérification des mots de passe.  
- Les éventuels facteurs d’authentification supplémentaires.  
- La gestion du cycle de vie des identifiants (création, mise à jour, suppression).  
====

**Authentification par mot de passe :**

====
Exemple 1 : L’authentification des internautes inscrits se fera par **login/mot de passe**, en respectant la politique de mot de passe `P`.  
Les mots de passe seront hachés et stockés sous forme de digest **bcrypt avec un facteur de coût de 12**.
====
====
Exemple 2 : Les administrateurs internes utiliseront un **SSO basé sur Kerberos** avec délégation via un fournisseur d’identité OAuth2/OpenID Connect.
====
====
Exemple 3 : Pour permettre la récupération de compte, les utilisateurs pourront réinitialiser leur mot de passe via **un lien temporaire envoyé par e-mail** (valable 10 minutes).
====

**Authentification forte (2FA/MFA) :**

====
Exemple 4 : Lors de l’ajout d’un nouveau bénéficiaire de virement dans l’espace internet, l’utilisateur devra fournir :  
  - Son mot de passe habituel.  
  - Un **OTP** généré via une application TOTP (Google Authenticator, FreeOTP…).  
====
====
Exemple 5 : L'accès aux API REST critiques nécessitera une **authentification par clé API + JWT signé**.  
Les clés API seront stockées dans un **Vault** et soumises à une rotation automatique.
====

**Sécurisation des authentifications sensibles: **
====
Exemple 6 : Toute tentative d’authentification échouée sera **journalisée et supervisée**.  
Après **5 échecs successifs**, le compte sera **verrouillé temporairement pendant 30 minutes**.
====
====
Exemple 7 : Les connexions suspectes (nouvelle adresse IP, localisation inhabituelle) nécessiteront une **vérification supplémentaire via un OTP envoyé par e-mail**.
====

//🏷{"id": "49de0015-9e27-4f60-91ca-282feec8345d", "labels": ["niveau::avancé","niveau_detail::détaillé"], "link_to": ["f552f1e6-9aea-4866-8da1-e7ed676fd228"]}
### Fédération d’identité

[TIP]
====
Les solutions les plus courantes sont actuellement :

- **OpenID Connect (OIDC)** : protocole moderne basé sur OAuth2, adapté aux applications Web et mobiles.
- **SAML** : utilisé principalement pour le SSO en entreprise (ADFS, Shibboleth, Okta…).
- **OAuth 2.0** : uniquement pour **l’autorisation**, pas l’authentification (pseudo-authentification possible via un IdP complémentaire).

Pour les applications Web, préciser les **contraintes navigateur** (gestion des cookies, SameSite policy…).
====

====
Exemple  : L’IHM grand public permettra une identification et authentification via **France Connect** (basé sur OpenID Connect).  
Les utilisateurs pourront s’identifier en réutilisant leur compte **DGFiP, CNAM, etc.**  
====

//🏷{"id": "1c4774ab-e6fc-46a4-bb89-97e318a8dd8f", "labels": ["niveau::avancé", "niveau::avancé"],"link_to:":["400376ad-cc62-4ab3-8e96-5a9f9a954e49"]}
### SSO et SLO

[TIP]
====
Décrire ici la technologie choisie et son intégration dans l’architecture.  
Quelques solutions courantes : 

- **CAS** (Central Authentication Service)  
- **Keycloak**  
- **OpenAM**  
- **LemonLDAP::NG**  

Préciser les contraintes spécifiques aux applications Web, notamment la gestion des **cookies**, du **token session**, et les implications de **SameSite / CORS**.
====

====
Exemple 1 : L’IHM X intégrera un client **CAS spring-security** pour le SSO.  
Le serveur CAS utilisé sera **YYY** et le **realm d’authentification** utilisé sera basé sur l’**Active Directory (AD) Y**.
====
====
Exemple 2 : Comme toutes les applications du **portail métier**, l’IHM X devra implémenter le **Single Logout (SLO)** en **gérant les callbacks de déconnexion** du serveur CAS.
====
====
Exemple 3 : Le SSO sera mis en œuvre via **Keycloak** en tant que fournisseur d’identité, avec une délégation vers l’AD via **LDAP**.
====

//🏷{"id": "8e35ee35-b5bc-433b-8389-f07e62a05339", "labels": ["niveau_detail::détaillé"]}
### Comptes de service

[TIP]
====
Les **comptes de service** sont utilisés pour authentifier une application ou un batch lorsqu’ils accèdent à un service d’infrastructure (base de données, API…).

**Bonnes pratiques :**

- **Stockage sécurisé** des credentials (éviter le stockage en clair dans la configuration).
- **Rotation automatique** des secrets si possible (HashiCorp Vault, AWS Secrets Manager…).
- **Permissions minimales** (Principe du Moindre Privilège).
====

.Comptes de service
[cols='1,2,2']
|===
|Compte | Ressource requérant authentification | Mode de stockage des credentials

|`jdbc_app` | Base de données PostgreSQL et SQL Server | **Stockage comme secret Kubernetes** (monté en volume uniquement sur les pods concernés)
|`api_backend` | API REST X | **Authentification via JWT signé et stocké dans un coffre-fort numérique sécurisé**
|`ci_cd_runner` | Serveur CI/CD | **Stockage en HashiCorp Vault avec rotation automatique des secrets**
|===

//🏷{"id": "9f09dacf-d151-45af-a5f6-209823e7a401", "labels": ["niveau::avancé"],"link_to":["01404b83-f96f-4649-ace0-e5611601b830"]}
### Non-répudiation et horodatage

====
Exemple : La déclaration d’impôt sera signée par le certificat client de l’usager (*X.509*, *RSA*, *SHA-256*) qui lui a été fourni par l'organisation X.
====

[TIP]
====
L'**horodatage cryptographique** ne répond pas à un besoin isolé mais est souvent utilisé en **complément d'une signature électronique** pour garantir la non-répudiation.  
L’horodatage permet de prévenir toute **altération de date** (*antidatage ou postdatage*).  
Il repose sur des **jetons d’horodatage qualifiés** (*RFC 3161, eIDAS*), délivrés par un **Prestataire de Service de Confiance (TSA – Timestamping Authority)**.

====

====
Exemple : Les signatures électroniques seront **horodatées** avec un **jeton d’horodatage qualifié eIDAS**, délivré par le **prestataire de service de confiance XYZ**.
====

//🏷{"id": "72efb92f-13f8-48e5-aed1-b57c4eab56fc", "labels": [],"link_to":["958fcccc-60cb-4158-940f-279cd1d12c9b"]}
### Anonymat et vie privée

====
Exemple 1 : Un **audit interne annuel** sera mené sur :

- Le **contenu des bases de données**.
- Les **extractions de données** à destination des partenaires externes.
====
====
Exemple 2 : Les données exposées publiquement seront **exportées partiellement** via :  
`COPY (SELECT <colonnes_autorisées> FROM table) TO <fichier>`  
Les **colonnes sensibles seront exclues** de la réplication vers la zone publique.
====

====
Exemple 3 : Un **bandeau de consentement aux cookies** sera mis en place sur toutes les pages de l’application **Angular** via le module `angular-cookie-law`.
====

//🏷{"id": "e6d0ad26-40b7-412e-b861-1f8e6e2299ca", "labels": ["niveau::intermédiaire"],"link_to":["fcad5990-c241-4c88-b2c5-646602f8935a"]}
### Habilitations

====
Exemple 1 : La gestion des **autorisations** sera intégrée **applicativement** et stockée dans la **base PostgreSQL**.  
Les tables dédiées aux autorisations seront détaillées dans le **dossier de spécification**.
====
====
Exemple 2 : L’accès aux **carnets d’adresses** sera contrôlé via **OAuth2**.  
L’API utilisée sera **Google OAuth2 en Java**.
====

//🏷{"id": "3819b8cc-d9c4-4d29-9ca1-adae300a79e2", "labels": ["niveau::intermédiaire"],"link_to":["e72e5ea5-5711-4665-8a91-76c63cbca2bc"]}
### Traçabilité et auditabilité

====
Exemple 1 : À la fin de chaque **action métier**, l’application **ReactJS** effectuera un **appel asynchrone** à un service REST dédié à la **traçabilité des actions**.  
Ce service enregistrera les **traces métier** dans une **base Elasticsearch** pour consultation via **Kibana**.
====
====
Exemple 2 : Un système de **détection d'intrusion (IDS)** hybride (*réseau + hôte*), basé sur **Wazuh**, sera **déployé sur l’ensemble des machines** utilisées par l’application.
====
====
Exemple 3 : Les **tables X, Y, …** seront **historisées** selon le modèle suivant : +
<diagramme de classe décrivant la conservation des versions de données>
====
====
Exemple 4 : Tous les documents **servant de preuve** seront archivés dans la **GED (Gestion Électronique de Documents)** avec des métadonnées permettant leur indexation et leur consultation rapide.
====
====
Exemple 5 : Les journaux **contenant le tag `[PREUVE]`** et issus de **tous les modules** seront :

- **Centralisés** via le système de logs **Elasticsearch**.
- **Transformés et enrichis** via **Logstash**.
- **Indexés quotidiennement** dans l’index **Elastic `preuves`** pour faciliter les recherches et la conformité.
====

//🏷{"id": "5e00eeef-1d5b-4a21-ac19-116ae376d999", "labels": ["niveau::intermédiaire"]}
### Lutte contre les cybermenaces

[TIP]
====
Les cybermenaces incluent : malwares, phishing, attaques DOS/DDOS, exploitation de vulnérabilités (connues ou zero-day), ingénierie sociale, escroqueries en ligne, fuites de données sensibles, etc.

Le cadre de réponse aux menaces peut être aligné sur le **NIST Cybersecurity Framework**, qui définit 5 fonctions clés :

1. **Identifier** : Comprendre et prioriser les risques.
2. **Protéger** : Mettre en place des mécanismes de défense.
3. **Détecter** : Identifier une attaque en cours.
4. **Réagir** : Contenir et neutraliser la menace.
5. **Récupérer** : Restaurer les services après une attaque.

//🏷{"id": "d13f2885-ab5c-4543-9432-f53002c01c2c", "labels": []}
#### Solutions de prévention

Ces solutions permettent d’**anticiper** les menaces avant qu'elles ne surviennent.

* **Formations et sensibilisations** des utilisateurs et des équipes IT.
* S’assurer que les développeurs connaissent et appliquent les mesures de mitigation issues du **https://owasp.org/www-project-top-ten/[OWASP Top 10]**, les bonnes pratiques de sécurité applicative (ex. : protection contre les injections, l’authentification défaillante, les conceptions non sécurisées et autres risques critiques).  

* **Systèmes de prévention d'intrusion (IPS)** pour bloquer les acteurs jugés malicieux.
* **Revues d'autorisations régulières** pour minimiser l'exposition.
* **Durcissement des règles de sécurité** :
  - Authentification à facteurs multiples (MFA).
  - Rotation obligatoire des mots de passe.
  - Utilisation de **coffres-forts numériques** pour stocker les secrets.
* **Audits réguliers** (tests d'intrusion, audit de code) par des experts internes ou externes.
* **Solutions DLP (Data Loss Prevention)** pour surveiller et empêcher les fuites de données sensibles.
* **Blocage des vecteurs d'attaque** (ex. désactivation des ports USB).
* **Mises à jour automatiques des patches de sécurité**.
====
====
Exemple 1 : Sensibilisation des utilisateurs via https://cyber.gouv.fr/bonnes-pratiques-protegez-vous[les recommandations de l'ANSSI].
====

====
Exemple 2 : Mise en place de l'IPS OpenSource **CrowdSec**, basé sur le partage d'information communautaire (*crowdsourcing*).
====

//🏷{"id": "ac7dde83-27c9-4916-9020-73efaab5fcb1", "labels": []}
#### Solutions de détection
[TIP]
====
Ces solutions permettent d’**identifier** les attaques en cours.

* **Antivirus nouvelle génération** (basés sur IA et heuristiques, et non uniquement sur des signatures).
* **WAF (Web Application Firewall)** pour analyser et bloquer les attaques applicatives.
* **SIEM (Security Information and Event Management)** pour corréler et analyser les journaux issus de multiples sources.
* **IDS (Intrusion Detection System)** pour surveiller le trafic réseau et détecter les attaques.
* **SAST (Static Application Security Testing)** et **DAST (Dynamic Application Security Testing)** :
  - SAST : Analyse du **code source** pour identifier les vulnérabilités connues.
  - DAST : Analyse des **comportements en exécution**.
* **SCA (Software Composition Analysis)** : Analyse des dépendances logicielles pour détecter les **CVE (Common Vulnerabilities and Exposures)**.
====
====
Exemple 1 : Intégration de **OWASP Dependency-Check** dans la CI/CD pour détecter les librairies contenant des CVE.
====

//🏷{"id": "d4498522-32aa-4987-aaec-2d9cf01130da", "labels": []}
#### Solutions de correction
[TIP]
====
Ces solutions permettent de **réagir** et **corriger** après la détection d’une menace.

* **Solutions anti-malware** pour supprimer les logiciels malveillants.
* **Plans de restauration des sauvegardes** pour reprendre l’activité rapidement (**MTTR** optimisé).
* **Isolation des zones compromises** (micro-segmentation réseau, cloisonnement des applications).
* **Gestion de parc logiciel** pour **bloquer** les logiciels non autorisés.
* **Analyse forensique** pour comprendre les chemins d'attaque et identifier la source d’une compromission.
* **Procédures de réponse à incident**, en se basant sur le standard **NIST SP 800-61**.
====
====
Exemple 1 : Déploiement d’un **plan de secours** basé sur les recommandations du https://www.cybermalveillance.gouv.fr/tous-nos-contenus/bonnes-pratiques/cyberattaque-que-faire-guide-dirigeants[NIST SP 800-61].
====

//🏷{"id": "a69b42f5-4f4e-42bf-b4bc-c6093941600f", "labels": ["niveau::avancé"]}
#### Solutions de prédiction
[TIP]
====
Ces solutions récentes reposent sur **l’analyse comportementale** et le **Machine Learning**.

* **UEBA (User and Entity Behavior Analytics)** : Détection des comportements anormaux d’utilisateurs ou de systèmes.
* **Simulations d'attaques complexes** pour tester la résilience du SI.
* **Threat Intelligence** : Intégration de flux de renseignement sur les menaces en temps réel.
====
====
Exemple 1 : Surveillance des comportements suspects via **AWS GuardDuty** sur une application cloud AWS.
====

====
Exemple 2 : Utilisation de **CrowdSec Threat Intelligence** pour anticiper les tendances d’attaques.
====

//🏷{"id": "d4d0f075-dff9-4d81-aebc-bbd0cc45bb55", "labels": ["annexe"]}
## Annexes

//🏷{"id": "b2f76b28-83da-478b-bc94-f1bc29dc6084", "labels": ["niveau::intermédiaire", "niveau_detail::détaillé"]}
### RACI & Gouvernance de la Sécurité

[TIP]
====
Ce RACI permet de définir clairement les rôles et responsabilités des équipes en matière de **gestion de la sécurité informatique**.

:r: pass:quotes[[.green]#R#]
:a: pass:quotes[[.red]#A#]
:c: pass:quotes[[.blue]#C#]
:i: pass:quotes[[.orange]#I#]
:na: pass:quotes[[.grey]#N/A#]
:et: pass:quotes[[.grey]#&amp;#]

* {r} : *Responsible* (exécute l'action).
* {a} : *Accountable* (valide l'action et en est responsable devant l'organisation).
* {c} : *Consulted* (doit être consulté pour expertise).
* {i} : *Informed* (doit être informé après réalisation).

Dans un bon RACI, il ne doit **jamais** y avoir plus d'un {a} pour chaque ligne.

Exemple: 

.Gestion des services Cloud AWS
[cols="6,^1,^1,^1"]
|===
||Équipe Systèmes & Cloud|Équipe Sécurité SI|Équipe Réseau

.^|Création des comptes AWS
.^|{r} {et} {a}
.^|{c} {et} {i}
.^|{i}

.^|Création des stratégies IAM & SCP AWS
.^|{r}
.^|{a}
.^|{c}

.^|Gestion des logs CloudTrail et alertes CloudWatch
.^|{r}
.^|{a}
.^|{i}
|===

.Gestion des comptes applicatifs & IAM
[cols="6,^1,^1,^1"]
|===
||Équipe annuaire|Équipe projet|Équipe SOC

.^|Création des comptes SSO
.^|{r} {et} {a}
.^|{i}
.^|{i}

.^|Gestion des accès
.^|{i}
.^|{r} {et} {a}
.^|{c}

.^|Revue annuelle des accès
.^|{c} {et} {i}
.^|{i}
.^|{r} {et} {a}

|===

====

[PRE-FILLED]
====
Ce RACI permet de définir clairement les rôles et responsabilités des équipes en matière de **gestion de la sécurité informatique**.

:r: pass:quotes[[.green]#R#]
:a: pass:quotes[[.red]#A#]
:c: pass:quotes[[.blue]#C#]
:i: pass:quotes[[.orange]#I#]
:na: pass:quotes[[.grey]#N/A#]
:et: pass:quotes[[.grey]#&amp;#]

* {r} : *Responsible* (exécute l'action).
* {a} : *Accountable* (valide l'action et en est responsable devant l'organisation).
* {c} : *Consulted* (doit être consulté pour expertise).
* {i} : *Informed* (doit être informé après réalisation).
====

//🏷{"id": "7d8dff71-3acd-450b-bc68-d2e2efee2fbb", "labels": ["niveau::intermédiaire","niveau_detail::détaillé"]}
### Auto-contrôles de sécurité

//🏷{"id": "68556bb6-b10d-4fe3-b956-ae9c5f926f4a", "labels": []}
#### Auto-contrôle des vulnérabilités

[TIP]
====
La gestion des vulnérabilités suit les standards **OWASP Top 10**, **MITRE ATT&CK** et **NIST 800-53**.

Objectif : Vérifier que les mesures de **protection, détection et correction** sont bien appliquées pour réduire les risques d'attaques (ex: ransomware, attaques supply-chain, injections...).

Exemple : 

[cols="e,e,3e"]
|===
|Vulnérabilité |Prise en compte ? |Mesures techniques entreprises

|Exposition de ports inutiles
|✅
|Configuration du firewall **iptables/nftables**. Seuls les ports 443 et 22 sont ouverts.

|Brute-force SSH
|✅
|Utilisation de **Fail2Ban** + authentification SSH par clé publique.

|Contournement des contrôles d’accès
|✅
|Utilisation de **Spring Security**, **OAuth2** et **RBAC**.

|Injection SQL / NoSQL
|✅
|Utilisation **exclusivement** de **Prepared Statements** et ORM sécurisés.

|XSS (Cross-Site Scripting)
|✅
a|
* Échappement systématique des entrées utilisateur avec **OWASP Java Encoder**.
* **CSP (Content-Security-Policy)** activé pour limiter l'exécution de scripts non autorisés.

|Fuite de secrets et API Keys
|✅
|Utilisation de **Vault** pour stocker les secrets.

|Attaques HTTPS (CRIME, BREACH, DROWN)
|✅
a|
* **Désactivation SSLv2 / SSLv3**
* Activation **HSTS (HTTP Strict Transport Security)**

|CSRF (Cross-Site Request Forgery)
|✅
|Utilisation du **double submit cookie pattern** et validation des tokens CSRF.

|Planification des mises à jour de sécurité
|✅
a|
* Mises à jour **Debian/Ubuntu** via **unattended-upgrades** chaque semaine.
* Mises à jour **PostgreSQL** appliquées dans un délai de **7 jours** après publication d'un CVE.
|===

====

[PRE-FILLED]
====

[cols="1,1,3"]
|===
|Vulnérabilité |Prise en compte ? |Mesures techniques entreprises

| 
| ✅
| 
|===
====

//🏷{"id": "f40cd11b-8d1f-4223-944d-3cad1a1a9f15", "labels": ["juridique"]}
#### Auto-contrôle RGPD

[TIP]
====
Le RGPD impose des exigences fortes sur les données personnelles des individus. Ces points sont basés sur les recommandations de la **CNIL** et de l'**EDPB**.

A noter que le RGPD **ne concerne que les personnes physiques**, pas les entreprises.

Exemple :

[cols="e,e,e"]
|===
|Exigence RGPD |Prise en compte ? |Mesures techniques entreprises

|Registre des traitements
|✅
|Documentation complète dans **Confluence / Notion**.

|Minimisation des données collectées
|✅
|Suppression des **numéros de CB stockés inutilement**.

|Droits des utilisateurs (accès, rectification, suppression)
|✅
|Un formulaire dédié permet d'effectuer les demandes de droit **via un workflow automatisé**.

|Protection des données sensibles
|✅
a|
* Chiffrement des backups en **AES-256**.
* Stockage des mots de passe en **bcrypt**.
|===
====

[PRE-FILLED]
====
[cols="1,1,1"]
|===
|Exigence RGPD |Prise en compte ? |Mesures techniques entreprises

| 
| ✅
| 
|===

====