@startuml
!include C4/C4_Deployment.puml
title archi-infra
header Diagramme de déploiement \nArchitecture d'infrastucture \n Projet Mes Informations En Ligne \n (partiel)
LAYOUT_WITH_LEGEND()

Node("client","Client","Desktop/mobile"){
  Node("nav1","Navigateur Web","Chrome/Firefox/Safari"){
    Container("spa","Application SPA MIEL","React.js")
  }
}

Node("dc","Datacenter","Paris"){
    Node("r2","Firewall","Cisco Firepower 4100")
    Node("lb1","LB Debian lb1","<<actif>>")
    Node("lb2","LB Debian lb2","<<passif>>")

    Node("rp1","Reverse Proxy","x2 Debian Buster <<actif/actif>>"){
      Container("ha1","Reverse Proxy","HaProxy")
    }

    Node("serveur_ihm", "Serveur IHM MIEL","x2 Debian Buster") { 
      Node("sw1","Serveur Web","Nginx"){
        Container("ihms1","Application Web SPA","React.js","Expose les resources statiques\n (.js, .html, images...)")
      }
      Node("tomcat_batchs1","Serveur JEE","Tomcat 10"){
        Container("batch1","batch-traiter-demandes","Java","Traite les demandes\n scheduling: * * * * *")
      }
    }

    Node("serveur_api","Serveur API","x3, RHEL") { 
      Node("wilfly1","Serveur JEE","Wildfly") {
        Container("api1","API service-miel","Java")        
      }
    }

    Node("bdd1", "Serveur BDD","RHEL")  { 
      ContainerDb("pg1","PostgreSQL","PostgreSQL 12")
      ContainerDb("mq1", "File de messages", "RabbitMQ")
      Container("mail1","MTA","Postfix")
    }

    Node("serveur_sup1", "Serveur Supervision","x1 Debian Stretch") {
      Container("sup1","Outil de supervision","Centreon")      
    }

    Node("ech1","Serveur Echange","x1 Windows Server") {
      Container("gw1","API Gateway","Axway API Gateway")    
    }

    ContainerDb("baie1","SAN EMC","baie 1")
    Node("tous_serveurs","<tous serveurs>","Supervision")
}

spa -> r2 : HTTPS sur Internet
r2 --> lb1 : HTTPS
lb2 -> lb1 : Heartbeat VRRP
lb1 -> ha1
ha1 --> ihms1 : HTTP
api1 --> mq1 : produit\n JMS / RabbitMQ
batch1 -->  mq1 : consomme\n JMS / RabbitMQ
api1 -->  pg1 : JDBC / PG
batch1 -->  mail1 : SMTP / envoi des mails
api1 -->  gw1 : SOAP/HTTPS
ha1 --> api1 : REST /HTTP
sup1 --> tous_serveurs : SNMP

Rel_Left("bdd1","baie1","FC")

@enduml

