@startuml archi-applicative-detaillee-inventaire
!include <C4/C4_Container>
header Diagramme de conteneurs \nVue inventaire \n Projet Mes Infos En Ligne (MIEL)
LAYOUT_WITH_LEGEND()

System_Boundary(company_system, "SI d'une entreprise") {
  Person_Ext(entreprise, "Entreprise","[person] \nClient Web (PC, tablette, mobile)")
  Container(spa, "SPA ihm-miel", "Container: javascript, React.js","Interface graphique permettant de demander ses informations")
  Container(mobile, "Application mobile MIEL", "Container: Android","Interface graphique permettant de demander ses informations")
}

System_Boundary(administration, "Système administration B") {
    System_Ext(scompta, "Système comptabilité","Service REST") 
}

System_Boundary(si, "Système d'information"){
    Container(resources_statiques, "Application Web ihm-miel", "Container: nginx","Délivre les ressources statiques (js, html, images...) de l'IHM MIEL")
    Container(sm, "service-miel", "Container: Tomcat, Spring Boot","Service REST permettant de faire une demande d'informations")
    Container(batch, "batch-traiter-demandes", "Container: groovy","Traite les demandes, lancé par cron toutes les minutes")
    ContainerDb(file,"file-demandes","Container: ActiveMQ","Stocke les demandes")
    ContainerDb(bdd,"bdd-miel","Container: PostgreSQL","Base interne")
    Container(compo,"service-compo-pdf","Container: Wildfly + JasperReport", "Service REST de composition")
    Container(smails,"serveur-mail","Container: Postfix","Envoi les e-mails")     
}
@enduml


