@startuml
!includeurl https://raw.githubusercontent.com/kirchsth/C4-PlantUML/master/C4_Deployment.puml
title Diagramme de déploiement \nArchitecture d'infrastucture \n Projet Mes Informations En Ligne \n (partiel)
LAYOUT_WITH_LEGEND()

Deployment_Node("client","Client","Desktop/mobile"){
  Deployment_Node("nav1","Navigateur Web","Chrome/Firefox/Safari"){
    ContainerInstance("spa","Application SPA MIEL","React.js")
  }
}

Deployment_Node("dc","Datacenter","Paris"){
    Deployment_Node("r2","Firewall","Cisco Firepower 4100")
    Deployment_Node("lb1","LB Debian lb1","<<actif>>")
    Deployment_Node("lb2","LB Debian lb2","<<passif>>")

    Deployment_Node("rp1","Reverse Proxy","x2 Debian Buster <<actif/actif>>"){
      ContainerInstance("ha1","Reverse Proxy","HaProxy")
    }

    Deployment_Node("serveur_ihm", "Serveur IHM MIEL","x2 Debian Buster") { 
      Deployment_Node("sw1","Serveur Web","Nginx"){
        ContainerInstance("ihms1","Application Web SPA","React.js","Expose les resources statiques\n (.js, .html, images...)")
      }
      Deployment_Node("tomcat_batchs1","Serveur JEE","Tomcat 10"){
        ContainerInstance("batch1","batch-traiter-demandes","Java","Traite les demandes\n scheduling: * * * * *")
      }
    }

    Deployment_Node("serveur_api","Serveur API","x3, RHEL") { 
      Deployment_Node("wilfly1","Serveur JEE","Wildfly") {
        ContainerInstance("api1","API service-miel","Java")        
      }
    }

    Deployment_Node("bdd1", "Serveur BDD","RHEL")  { 
      ContainerInstanceDb("pg1","PostgreSQL","PostgreSQL 12")
      ContainerInstanceDb("mq1", "File de messages", "RabbitMQ")
      ContainerInstance("mail1","MTA","Postfix")
    }

    Deployment_Node("serveur_sup1", "Serveur Supervision","x1 Debian Stretch") {
      ContainerInstance("sup1","Outil de supervision","Centreon")      
    }

    Deployment_Node("ech1","Serveur Echange","x1 Windows Server") {
      ContainerInstance("gw1","API Gateway","Axway API Gateway")    
    }

    ContainerInstanceDb("baie1","SAN EMC","baie 1")
    Deployment_Node("tous_serveurs","<tous serveurs>","Supervision")
}

spa -> r2 : HTTPS sur Internet
r2 --> lb1 : HTTPS
lb2 -> lb1 : Heartbeat VRRP
lb1 -> ha1
ha1 --> ihms1 : HTTP
api1 --> mq1 : produit\n JMS / RabbitMQ
batch1 -->  mq1 : consomme\n JMS / RabbitMQ
api1 -->  pg1 : JDBC / PG
batch1 -->  mail1 : SMTP / envoi des mails
api1 -->  gw1 : SOAP/HTTPS
ha1 --> api1 : REST /HTTP
sup1 --> tous_serveurs : SNMP

Rel_Left("bdd1","baie1","FC")

@enduml

