@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
title  Diagramme de contexte système \nPoint de vue applicatif général \ndu projet Mes Infos En Ligne (MIEL)
LAYOUT_WITH_LEGEND()
Person_Ext(entreprise, "Entreprise","[Personne]")

System_Boundary(administration, "Système administration B") {
    System(p1, "Système comptabilité")        
}

System_Boundary(si, "Système d'information"),{
  System(ma, "MIEL","Permet aux entreprises de récupérer leurs données")
  System(ref1, "REF_ENTREPRISE","Référentiel personne")
  System(compo, "Système de composition","Editique transactionnelle"){        
}

Rel(entreprise, ma, "[1] Demande via formulaire")
Rel(ma, ref1, "[2.1] Enrichissement avec données internes")
Rel(ma, p1, "[2.2] Récupération informations comptables")
Rel(ma, compo, "[3] Création PDF")

@enduml